// AUTO-GENERATED by scripts/jwf-port/gen.ts — do not edit by hand.
// JWildfire ports that did NOT pass the oracle harness (see scripts/jwf-port/verified.json);
// kept out of the app registry, loaded only by the dev harness (src/dev/varTest.ts).

import type { JwfVariationDef } from './variations.jwf';

export const JWF_VARIATIONS_UNVERIFIED: Record<string, JwfVariationDef> = {
  "julia3D": {
    params: [{ name: "power", def: 3 }],
    verified: false, priority: 0, flags: ["3d","z"], types: ["3D"],
    funcNames: ["roundc","powc"],
    funcs: `fn roundc(x: f32) -> f32 { return sign(x) * floor(abs(x) + 0.5); }

fn powc(x: f32, y: f32) -> f32 {
  if (x >= 0.0) { return pow(x, y); }
  let yi = round(y);
  if (abs(y - yi) > 1e-6) { return pow(x, y); }
  let m = pow(-x, y);
  return select(m, -m, (i32(yi) & 1) != 0);
}`,
    code: (w, p) => `{
var n: f32 = f32(i32(roundc(${p[0]})));
n = select(n, 1.0, (n == 0.0));
var absn: f32 = abs(n);
var cn: f32 = (((1.0 / n) - 1.0) / 2.0);
var _z: f32 = (z_ / absn);
var r_: f32 = (${w} * powc((r2 + (z_ * z_)), cn));
var tmp: f32 = (r_ * r);
var cosa: f32;
var sina: f32;
sina = sin(((atan2(t.y, t.x) + ((2.0 * PI) * f32(i32(roundc(((rnd(rs) * absn) - 0.5)))))) / n));
cosa = cos(((atan2(t.y, t.x) + ((2.0 * PI) * f32(i32(roundc(((rnd(rs) * absn) - 0.5)))))) / n));
v.x += (tmp * cosa);
v.y += (tmp * sina);
pz_ += (r_ * _z);
}`,
  },
  "arch": {
    params: [],
    verified: false, priority: 0, flags: [], types: ["2D"],
    code: (w, _p) => `{
var rn: f32;
rn = rnd(rs);
var v_: f32 = ${w};
v.x += (v_ * sin(((rn * PI) * v_)));
v.y += ((v_ * sin(((rn * PI) * v_))) * tan(((rn * PI) * v_)));
}`,
  },
  "rays": {
    params: [],
    verified: false, priority: 0, flags: [], types: ["2D"],
    code: (w, _p) => `{
var rn: f32;
rn = rnd(rs);
var v_: f32 = ${w};
var r2inv_eps: f32 = (1.0 / (r2 + 1.0e-20));
var front: f32 = ((v_ * tan(((rn * PI) * v_))) * r2inv_eps);
v.x += ((v_ * front) * cos(t.x));
v.y += ((v_ * front) * sin(t.y));
}`,
  },
  "post_mirror_wf": {
    params: [{ name: "xaxis", def: 1 }, { name: "yaxis", def: 0 }, { name: "zaxis", def: 0 }, { name: "xshift", def: 0 }, { name: "yshift", def: 0 }, { name: "zshift", def: 0 }, { name: "xscale", def: 1 }, { name: "yscale", def: 1 }, { name: "xcolorshift", def: 0 }, { name: "ycolorshift", def: 0 }, { name: "zcolorshift", def: 0 }],
    verified: false, priority: 1, flags: ["dc","z"], types: ["2D","DC","POST"],
    code: (_w, p) => `{
if (((${p[0]} > 0.0) && (rnd(rs) < 0.5))) {
  v.x = (-v.x - ${p[3]});
  (*cp) = (((*cp) + ${p[8]}) % 1.0);
}
if (((${p[1]} > 0.0) && (rnd(rs) < 0.5))) {
  v.y = (-v.y - ${p[4]});
  (*cp) = (((*cp) + ${p[9]}) % 1.0);
}
if (((${p[2]} > 0.0) && (rnd(rs) < 0.5))) {
  pz_ = (-pz_ - ${p[5]});
  (*cp) = (((*cp) + ${p[10]}) % 1.0);
}
}`,
  },
  "post_colorscale_wf": {
    params: [{ name: "scale_x", def: 0 }, { name: "scale_y", def: 0 }, { name: "scale_z", def: 0.5 }, { name: "offset_z", def: 0 }, { name: "reset_z", def: 0 }, { name: "sides", def: 0 }],
    verified: false, priority: 1, flags: ["3d","dc","z"], types: ["3D","POST"],
    funcNames: ["roundc"],
    funcs: `fn roundc(x: f32) -> f32 { return sign(x) * floor(abs(x) + 0.5); }`,
    code: (w, p) => `{
v.x += ((${w} * ${p[0]}) * v.x);
v.y += ((${w} * ${p[1]}) * v.y);
var dz: f32 = ((((*cp) * ${p[2]}) * ${w}) + ${p[3]});
if ((i32(roundc(${p[4]})) > 0)) {
  pz_ = dz;
} else {
  if ((i32(roundc(${p[5]})) > 0)) {
    pz_ += (dz * rnd(rs));
  } else {
    pz_ += dz;
  }
}
}`,
  },
  "post_falloff2": {
    params: [{ name: "scatter", def: 1 }, { name: "mindist", def: 0.5 }, { name: "mul_x", def: 1 }, { name: "mul_y", def: 1 }, { name: "mul_z", def: 0 }, { name: "mul_c", def: 0 }, { name: "x0", def: 0 }, { name: "y0", def: 0 }, { name: "z0", def: 0 }, { name: "invert", def: 0 }, { name: "type", def: 0 }],
    verified: false, priority: 1, flags: ["3d","dc","z"], types: ["3D","POST","BLUR"],
    funcNames: ["roundc","sqrf","fracf"],
    funcs: `fn roundc(x: f32) -> f32 { return sign(x) * floor(abs(x) + 0.5); }

fn sqrf(x: f32) -> f32 {
  return (x * x);
}

fn fracf(x: f32) -> f32 {
  return (x - trunc(x));
}`,
    code: (w, p) => `{
var _rmax: f32 = (0.04 * ${p[0]});
var pIn_x: f32 = v.x;
var pIn_y: f32 = v.y;
var pIn_z: f32 = pz_;
switch i32(roundc(${p[10]})) {
  case 1: {
    {
      var r_in: f32 = (sqrt((((pIn_x * pIn_x) + (pIn_y * pIn_y)) + (pIn_z * pIn_z))) + 0.000001);
      var d: f32 = sqrt(((sqrf((pIn_x - ${p[6]})) + sqrf((pIn_y - ${p[7]}))) + sqrf((pIn_z - ${p[8]}))));
      if ((i32(roundc(${p[9]})) != 0)) {
        d = (1 - d);
      }
      if ((d < 0)) {
        d = 0;
      }
      d = ((d - ${p[1]}) * _rmax);
      if ((d < 0)) {
        d = 0;
      }
      var sigma: f32 = (asin((pIn_z / r_in)) + ((${p[4]} * rnd(rs)) * d));
      var phi: f32 = (atan2(pIn_y, pIn_x) + ((${p[3]} * rnd(rs)) * d));
      var r_: f32 = (r_in + ((${p[2]} * rnd(rs)) * d));
      var sins: f32 = sin(sigma);
      var coss: f32 = cos(sigma);
      var sinp: f32 = sin(phi);
      var cosp: f32 = cos(phi);
      v.x += (${w} * ((r_ * coss) * cosp));
      v.y += (${w} * ((r_ * coss) * sinp));
      pz_ += (${w} * sins);
      (*cp) = abs(fracf(((*cp) + ((${p[5]} * rnd(rs)) * d))));
    }
  }
  case 2: {
    {
      var d: f32 = sqrt(((sqrf((pIn_x - ${p[6]})) + sqrf((pIn_y - ${p[7]}))) + sqrf((pIn_z - ${p[8]}))));
      if ((i32(roundc(${p[9]})) != 0)) {
        d = (1 - d);
      }
      if ((d < 0)) {
        d = 0;
      }
      d = ((d - ${p[1]}) * _rmax);
      if ((d < 0)) {
        d = 0;
      }
      var sigma: f32 = (((d * rnd(rs)) * 2) * PI);
      var phi: f32 = ((d * rnd(rs)) * PI);
      var r_: f32 = (d * rnd(rs));
      var sins: f32 = sin(sigma);
      var coss: f32 = cos(sigma);
      var sinp: f32 = sin(phi);
      var cosp: f32 = cos(phi);
      v.x += (${w} * (pIn_x + (((${p[2]} * r_) * coss) * cosp)));
      v.y += (${w} * (pIn_y + (((${p[3]} * r_) * coss) * sinp)));
      pz_ += (${w} * (pIn_z + ((${p[4]} * r_) * sins)));
      (*cp) = abs(fracf(((*cp) + ((${p[5]} * rnd(rs)) * d))));
    }
  }
  case default: {
    {
      var d: f32 = sqrt(((sqrf((pIn_x - ${p[6]})) + sqrf((pIn_y - ${p[7]}))) + sqrf((pIn_z - ${p[8]}))));
      if ((i32(roundc(${p[9]})) != 0)) {
        d = (1 - d);
      }
      if ((d < 0)) {
        d = 0;
      }
      d = ((d - ${p[1]}) * _rmax);
      if ((d < 0)) {
        d = 0;
      }
      v.x += (${w} * (pIn_x + ((${p[2]} * rnd(rs)) * d)));
      v.y += (${w} * (pIn_y + ((${p[3]} * rnd(rs)) * d)));
      pz_ += (${w} * (pIn_z + ((${p[4]} * rnd(rs)) * d)));
      (*cp) = abs(fracf(((*cp) + ((${p[5]} * rnd(rs)) * d))));
    }
  }
}
}`,
  },
  "xtrb": {
    params: [{ name: "power", def: 2 }, { name: "radius", def: 1 }, { name: "width", def: 0.5 }, { name: "dist", def: 1 }, { name: "a", def: 1 }, { name: "b", def: 1 }],
    verified: false, priority: 0, flags: [], types: ["2D"],
    funcNames: ["roundc","powc"],
    funcs: `fn roundc(x: f32) -> f32 { return sign(x) * floor(abs(x) + 0.5); }

fn powc(x: f32, y: f32) -> f32 {
  if (x >= 0.0) { return pow(x, y); }
  let yi = round(y);
  if (abs(y - yi) > 1e-6) { return pow(x, y); }
  let m = pow(-x, y);
  return select(m, -m, (i32(yi) & 1) != 0);
}`,
    code: (w, p) => `{
var width1: f32;
var width2: f32;
var width3: f32;
var sinC: f32;
var cosC: f32;
var ab: f32;
var ac: f32;
var ba: f32;
var bc: f32;
var ca: f32;
var cb: f32;
var Ha: f32;
var Hb: f32;
var Hc: f32;
var S2a: f32;
var S2b: f32;
var S2c: f32;
var S2bc: f32;
var S2ab: f32;
var S2ac: f32;
var absN: i32;
var cN: f32;
var power: i32 = i32(roundc(${p[0]}));
{
  var angle_Br: f32 = (0.047 + ${p[4]});
  var angle_Cr: f32 = (0.047 + ${p[5]});
  var angle_Ar: f32 = ((PI - angle_Br) - angle_Cr);
  var sinA2: f32;
  var cosA2: f32;
  sinA2 = sin((0.5 * angle_Ar));
  cosA2 = cos((0.5 * angle_Ar));
  var sinB2: f32;
  var cosB2: f32;
  sinB2 = sin((0.5 * angle_Br));
  cosB2 = cos((0.5 * angle_Br));
  var sinC2: f32;
  var cosC2: f32;
  sinC2 = sin((0.5 * angle_Cr));
  cosC2 = cos((0.5 * angle_Cr));
  sinC = sin(angle_Cr);
  cosC = cos(angle_Cr);
  var a: f32 = (${p[1]} * ((sinC2 / cosC2) + (sinB2 / cosB2)));
  var b: f32 = (${p[1]} * ((sinC2 / cosC2) + (sinA2 / cosA2)));
  var c: f32 = (${p[1]} * ((sinB2 / cosB2) + (sinA2 / cosA2)));
  width1 = (1.0 - ${p[2]});
  width2 = (2.0 * ${p[2]});
  width3 = (1.0 - (${p[2]} * ${p[2]}));
  var S2: f32 = (${p[1]} * ((a + b) + c));
  Ha = ((S2 / a) / 6.0);
  Hb = ((S2 / b) / 6.0);
  Hc = ((S2 / c) / 6.0);
  ab = (a / b);
  ac = (a / c);
  ba = (b / a);
  bc = (b / c);
  ca = (c / a);
  cb = (c / b);
  S2a = (6.0 * Ha);
  S2b = (6.0 * Hb);
  S2c = (6.0 * Hc);
  S2bc = ((S2 / (b + c)) / 6.0);
  S2ab = ((S2 / (a + b)) / 6.0);
  S2ac = ((S2 / c) / 6.0);
  absN = select(power, -power, (power < 0));
  cN = ((${p[3]} / f32(power)) / 2.0);
}
var Alpha: f32;
var Beta: f32;
var OffsetAl: f32;
var OffsetBe: f32;
var OffsetGa: f32;
var X: f32;
var Y: f32;
var M: i32;
var N: i32;
{
  var U: f32 = (t.y + ${p[1]});
  var V: f32 = (((t.x * sinC) - (t.y * cosC)) + ${p[1]});
  Alpha = U;
  Beta = V;
}
M = i32(floor((Alpha / S2a)));
OffsetAl = (Alpha - (f32(M) * S2a));
N = i32(floor((Beta / S2b)));
OffsetBe = (Beta - (f32(N) * S2b));
OffsetGa = ((S2c - (ac * OffsetAl)) - (bc * OffsetBe));
if ((OffsetGa > 0)) {
  var Al: f32 = OffsetAl;
  var Be: f32 = OffsetBe;
  var Ga: f32 = OffsetGa;
  var Ga1: f32;
  var De1: f32;
  var R: f32;
  R = rnd(rs);
  if ((Be < Al)) {
    if ((Ga < Be)) {
      if ((R >= width3)) {
        De1 = (${p[2]} * Be);
        Ga1 = (${p[2]} * Ga);
      } else {
        Ga1 = ((width1 * Ga) + (((width2 * Hc) * Ga) / Be));
        De1 = ((width1 * Be) + ((width2 * S2ab) * (3 - (Ga / Be))));
      }
      Alpha = ((S2a - (ba * De1)) - (ca * Ga1));
      Beta = De1;
    } else {
      if ((Ga < Al)) {
        if ((R >= width3)) {
          Ga1 = (${p[2]} * Ga);
          De1 = (${p[2]} * Be);
        } else {
          De1 = ((width1 * Be) + (((width2 * Hb) * Be) / Ga));
          Ga1 = ((width1 * Ga) + ((width2 * S2ac) * (3 - (Be / Ga))));
        }
        Alpha = ((S2a - (ba * De1)) - (ca * Ga1));
        Beta = De1;
      } else {
        if ((R >= width3)) {
          Alpha = (${p[2]} * Al);
          Beta = (${p[2]} * Be);
        } else {
          Beta = ((width1 * Be) + (((width2 * Hb) * Be) / Al));
          Alpha = ((width1 * Al) + ((width2 * S2ac) * (3 - (Be / Al))));
        }
      }
    }
  } else {
    if ((Ga < Al)) {
      if ((R >= width3)) {
        De1 = (${p[2]} * Al);
        Ga1 = (${p[2]} * Ga);
      } else {
        Ga1 = ((width1 * Ga) + (((width2 * Hc) * Ga) / Al));
        De1 = ((width1 * Al) + ((width2 * S2ab) * (3 - (Ga / Al))));
      }
      Beta = ((S2b - (ab * De1)) - (cb * Ga1));
      Alpha = De1;
    } else {
      if ((Ga < Be)) {
        if ((R >= width3)) {
          Ga1 = (${p[2]} * Ga);
          De1 = (${p[2]} * Al);
        } else {
          De1 = ((width1 * Al) + (((width2 * Ha) * Al) / Ga));
          Ga1 = ((width1 * Ga) + ((width2 * S2bc) * (3 - (Al / Ga))));
        }
        Beta = ((S2b - (ab * De1)) - (cb * Ga1));
        Alpha = De1;
      } else {
        if ((R >= width3)) {
          Beta = (${p[2]} * Be);
          Alpha = (${p[2]} * Al);
        } else {
          Alpha = ((width1 * Al) + (((width2 * Ha) * Al) / Be));
          Beta = ((width1 * Be) + ((width2 * S2bc) * (3 - (Al / Be))));
        }
      }
    }
  }
} else {
  OffsetAl = (S2a - OffsetAl);
  OffsetBe = (S2b - OffsetBe);
  OffsetGa = -OffsetGa;
  {
    var Al: f32 = OffsetAl;
    var Be: f32 = OffsetBe;
    var Ga: f32 = OffsetGa;
    var Ga1: f32;
    var De1: f32;
    var R: f32;
    R = rnd(rs);
    if ((Be < Al)) {
      if ((Ga < Be)) {
        if ((R >= width3)) {
          De1 = (${p[2]} * Be);
          Ga1 = (${p[2]} * Ga);
        } else {
          Ga1 = ((width1 * Ga) + (((width2 * Hc) * Ga) / Be));
          De1 = ((width1 * Be) + ((width2 * S2ab) * (3 - (Ga / Be))));
        }
        Alpha = ((S2a - (ba * De1)) - (ca * Ga1));
        Beta = De1;
      } else {
        if ((Ga < Al)) {
          if ((R >= width3)) {
            Ga1 = (${p[2]} * Ga);
            De1 = (${p[2]} * Be);
          } else {
            De1 = ((width1 * Be) + (((width2 * Hb) * Be) / Ga));
            Ga1 = ((width1 * Ga) + ((width2 * S2ac) * (3 - (Be / Ga))));
          }
          Alpha = ((S2a - (ba * De1)) - (ca * Ga1));
          Beta = De1;
        } else {
          if ((R >= width3)) {
            Alpha = (${p[2]} * Al);
            Beta = (${p[2]} * Be);
          } else {
            Beta = ((width1 * Be) + (((width2 * Hb) * Be) / Al));
            Alpha = ((width1 * Al) + ((width2 * S2ac) * (3 - (Be / Al))));
          }
        }
      }
    } else {
      if ((Ga < Al)) {
        if ((R >= width3)) {
          De1 = (${p[2]} * Al);
          Ga1 = (${p[2]} * Ga);
        } else {
          Ga1 = ((width1 * Ga) + (((width2 * Hc) * Ga) / Al));
          De1 = ((width1 * Al) + ((width2 * S2ab) * (3 - (Ga / Al))));
        }
        Beta = ((S2b - (ab * De1)) - (cb * Ga1));
        Alpha = De1;
      } else {
        if ((Ga < Be)) {
          if ((R >= width3)) {
            Ga1 = (${p[2]} * Ga);
            De1 = (${p[2]} * Al);
          } else {
            De1 = ((width1 * Al) + (((width2 * Ha) * Al) / Ga));
            Ga1 = ((width1 * Ga) + ((width2 * S2bc) * (3 - (Al / Ga))));
          }
          Beta = ((S2b - (ab * De1)) - (cb * Ga1));
          Alpha = De1;
        } else {
          if ((R >= width3)) {
            Beta = (${p[2]} * Be);
            Alpha = (${p[2]} * Al);
          } else {
            Alpha = ((width1 * Al) + (((width2 * Ha) * Al) / Be));
            Beta = ((width1 * Be) + ((width2 * S2bc) * (3 - (Al / Be))));
          }
        }
      }
    }
  }
  Alpha = (S2a - Alpha);
  Beta = (S2b - Beta);
}
Alpha = (Alpha + (f32(M) * S2a));
Beta = (Beta + (f32(N) * S2b));
{
  var inx: f32 = (((Beta - ${p[1]}) + ((Alpha - ${p[1]}) * cosC)) / sinC);
  var iny: f32 = (Alpha - ${p[1]});
  var angle: f32 = ((atan2(iny, inx) + ((2.0 * PI) * f32((i32(roundc((rnd(rs) * 8191))) % absN)))) / f32(power));
  var r_: f32 = (${w} * powc(((inx * inx) + (iny * iny)), cN));
  var sina: f32 = sin(angle);
  var cosa: f32 = cos(angle);
  X = (r_ * cosa);
  Y = (r_ * sina);
}
v.x += (${w} * X);
v.y += (${w} * Y);
}`,
  },
  "bwrands": {
    params: [{ name: "cellsize", def: 1 }, { name: "space", def: 0 }, { name: "gain", def: 1.25 }, { name: "inner_twist", def: 0 }, { name: "outer_twist", def: 0 }, { name: "seed", def: 3210 }, { name: "rrot", def: 1 }, { name: "rmin", def: 0.25 }, { name: "loonie_chance", def: 0.5 }, { name: "petals_chance", def: 0.5 }, { name: "minpetals", def: 3 }, { name: "maxpetals", def: 20 }],
    verified: false, priority: 0, flags: [], types: ["2D"],
    funcNames: ["sqrf","bwrands_bytemix","bwrands_byteshf","bwrands_bytexim","bwrands_byteprimes"],
    funcs: `fn sqrf(x: f32) -> f32 {
  return (x * x);
}

fn bwrands_bytemix(a: i32, b: i32) -> i32 {
  return ((a & 23130) ^ (b & 42405));
}

fn bwrands_byteshf(a: i32, b: i32) -> i32 {
  return (((a << 8) ^ (b >> 8)) & 65535);
}

fn bwrands_bytexim(a: i32, b: i32) -> i32 {
  return ((a & 43690) ^ (b & 21845));
}

fn bwrands_byteprimes(a: i32, b: i32) -> i32 {
  return ((((a * 857) - 4) & 65280) ^ (((-b * 977) + 8) & 255));
}`,
    code: (w, p) => `{
var _g2: f32;
var _r2: f32;
var _rfactor: f32;
var _petx: i32;
var _pety: i32;
var radius: f32 = (0.5 * (${p[0]} / (1.0 + (${p[1]} * ${p[1]}))));
_g2 = ((sqrf(${p[2]}) / radius) + 0.000001);
var max_bubble: f32 = (_g2 * radius);
if ((max_bubble > 2.0)) {
  max_bubble = 1.0;
} else {
  max_bubble *= (1.0 / (((max_bubble * max_bubble) / 4.0) + 1.0));
}
_r2 = (radius * radius);
_rfactor = (radius / max_bubble);
_petx = i32(min(min(max(${p[10]}, 1.0), 1000.0), min(max(${p[11]}, 1.0), 1000.0)));
_pety = i32(abs((min(max(${p[11]}, 1.0), 1000.0) - min(max(${p[10]}, 1.0), 1000.0))));
var Vx: f32;
var Vy: f32;
var Cx: f32;
var Cy: f32;
var Lx: f32;
var Ly: f32;
var r_: f32;
var theta: f32;
var s: f32;
var c: f32;
var Vv2: f32;
var flwr: f32;
Vx = t.x;
Vy = t.y;
if ((abs(${p[0]}) < 0.000001)) {
  v.x += (${w} * Vx);
  v.y += (${w} * Vy);
} else {
  var Ix: i32 = i32(floor((Vx / ${p[0]})));
  var Iy: i32 = i32(floor((Vy / ${p[0]})));
  Cx = ((f32(Ix) + 0.5) * ${p[0]});
  Cy = ((f32(Iy) + 0.5) * ${p[0]});
  var xx: i32 = (Ix ^ 46657);
  var yy: i32 = (Iy ^ 40321);
  var xy: i32 = i32((f32((xx * yy)) + ${p[5]}));
  xx &= 65535;
  yy &= 65535;
  xy &= 65535;
  var tt: i32 = bwrands_bytemix(xx, yy);
  yy = bwrands_bytemix(yy, xx);
  xx = tt;
  tt = bwrands_byteshf(xx, xy);
  yy = bwrands_byteshf(xy, yy);
  xx = tt;
  tt = bwrands_bytexim(xx, yy);
  yy = bwrands_bytexim(yy, xx);
  xx = tt;
  var Ssz: f32 = (f32(xx) / 65535.0);
  Ssz = (min(max(${p[7]}, 0.0), 1.0) + (Ssz * (1.0 - min(max(${p[7]}, 0.0), 1.0))));
  var Aan: f32 = (((min(max(${p[6]}, 0.0), 1.0) * (2.0 * PI)) * f32(yy)) / 65535.0);
  tt = bwrands_byteprimes(xx, yy);
  yy = bwrands_byteprimes(yy, xx);
  xx = tt;
  var LoonieChance: f32 = ((-(f32(xx)) / 65535.0) + min(max(${p[8]}, 0.0), 1.0));
  var PetalsChance: f32 = 0.0;
  if ((LoonieChance < 0)) {
    PetalsChance = (LoonieChance + min(max(${p[9]}, 0.0), 1.0));
  }
  var NPetals: f32;
  if ((_pety == 0)) {
    NPetals = f32(_petx);
  } else {
    NPetals = f32((_petx + ((yy >> 3) % (1 + _pety))));
  }
  if ((LoonieChance <= PetalsChance)) {
    LoonieChance = -1.0;
  }
  Lx = (Vx - Cx);
  Ly = (Vy - Cy);
  Vv2 = (Ssz * _r2);
  if ((((Lx * Lx) + (Ly * Ly)) > Vv2)) {
    v.x += (${w} * Vx);
    v.y += (${w} * Vy);
  } else {
    if ((LoonieChance > 0.0)) {
      r_ = ((Vv2 / ((Lx * Lx) + (Ly * Ly))) - 1.0);
      r_ = sqrt(r_);
      Lx *= r_;
      Ly *= r_;
      Vv2 = 1.0;
    } else if ((PetalsChance > 0.0)) {
      flwr = ((NPetals / (2.0 * PI)) * (PI + atan2(Ly, Lx)));
      flwr = (flwr - f32(i32(flwr)));
      flwr = (abs((flwr - 0.5)) * 2.0);
      r_ = sqrt(((Lx * Lx) + (Ly * Ly)));
      PetalsChance = rnd(rs);
      if ((PetalsChance < (0.5 * (flwr + 0.5)))) {
        Lx *= ((1.0 - r_) * (flwr * 1.1));
        Ly *= ((1.0 - r_) * (flwr * 1.1));
      } else {
        Vv2 = sqrt(Vv2);
        Lx *= ((Vv2 - (r_ * (1.0 - flwr))) / (r_ + 0.000001));
        Ly *= ((Vv2 - (r_ * (1.0 - flwr))) / (r_ + 0.000001));
      }
      Vv2 = 1.0;
    } else {
      Lx *= _g2;
      Ly *= _g2;
      r_ = (_rfactor / ((((Lx * Lx) + (Ly * Ly)) / (4.0 * Ssz)) + 1.0));
      Lx *= r_;
      Ly *= r_;
      Vv2 = sqrt(Ssz);
    }
    r_ = ((Vv2 * ((Lx * Lx) + (Ly * Ly))) / _r2);
    theta = ((${p[3]} * (1.0 - r_)) + (${p[4]} * r_));
    s = sin((theta + Aan));
    c = cos((theta + Aan));
    Vx = ((Cx + (c * Lx)) + (s * Ly));
    Vy = ((Cy - (s * Lx)) + (c * Ly));
    v.x += (${w} * Vx);
    v.y += (${w} * Vy);
  }
}
}`,
  },
  "cpow3": {
    params: [{ name: "r", def: 1 }, { name: "d", def: 1 }, { name: "divisor", def: 1 }, { name: "spread", def: 1 }],
    verified: false, priority: 0, flags: [], types: ["2D"],
    funcNames: ["roundc"],
    funcs: `fn roundc(x: f32) -> f32 { return sign(x) * floor(abs(x) + 0.5); }`,
    code: (w, p) => `{
var ang: f32;
var p_a: f32;
var tc: f32;
var half_c: f32;
var td: f32;
var half_d: f32;
var coeff: f32;
ang = ((2.0 * PI) / ${p[2]});
p_a = atan2((select(log(${p[1]}), -(log(-(${p[1]}))), (${p[1]} < 0)) * ${p[0]}), (2 * PI));
tc = (((cos(p_a) * ${p[0]}) * cos(p_a)) / ${p[2]});
td = (((cos(p_a) * ${p[0]}) * sin(p_a)) / ${p[2]});
half_c = (tc / 2.0);
half_d = (td / 2.0);
coeff = select(((-0.095 * ${p[3]}) / td), 0, (td == 0));
var a: f32 = ph;
if ((a < 0)) {
  a += (2 * PI);
}
if ((cos((a / 2)) < ((rnd(rs) * 2.0) - 1.0))) {
  a -= (2 * PI);
}
a += (select((-2 * PI), (2 * PI), (rnd(rs) < 0.5)) * roundc((log(rnd(rs)) * coeff)));
var lnr2: f32 = log(r2);
var r_: f32 = (${w} * exp(((half_c * lnr2) - (td * a))));
var th_: f32 = (((tc * a) + (half_d * lnr2)) + (ang * floor((${p[2]} * rnd(rs)))));
v.x += (r_ * cos(th_));
v.y += (r_ * sin(th_));
}`,
  },
  "post_point_symmetry_wf": {
    params: [{ name: "centre_x", def: 0.25 }, { name: "centre_y", def: 0.5 }, { name: "order", def: 3 }, { name: "colorshift", def: 0 }],
    verified: false, priority: 1, flags: ["dc"], types: ["2D","DC","POST"],
    funcNames: ["roundc"],
    funcs: `fn roundc(x: f32) -> f32 { return sign(x) * floor(abs(x) + 0.5); }`,
    code: (w, p) => `{
var order: i32 = i32(roundc(${p[2]}));
if ((order > 36)) {
  order = 36;
}
var _sina: array<f32, 36>;
var _cosa: array<f32, 36>;
var da: f32 = ((2.0 * PI) / f32(order));
var angle: f32 = 0.0;
for (var i: i32 = 0; (i < order); i++) {
  _sina[i] = sin(angle);
  _cosa[i] = cos(angle);
  angle += da;
}
var dx: f32 = ((v.x - ${p[0]}) * ${w});
var dy: f32 = ((v.y - ${p[1]}) * ${w});
var idx: i32 = i32(roundc((rnd(rs) * f32((order - 1)))));
v.x = ((${p[0]} + (dx * _cosa[idx])) + (dy * _sina[idx]));
v.y = ((${p[1]} + (dy * _cosa[idx])) - (dx * _sina[idx]));
(*cp) = (((*cp) + (f32(idx) * ${p[3]})) % 1.0);
}`,
  },
  "tile_hlp": {
    params: [{ name: "width", def: 1 }],
    verified: false, priority: 0, flags: [], types: ["2D"],
    code: (w, p) => `{
var width2: f32 = (${p[0]} * ${w});
var x: f32 = (t.x / ${p[0]});
var aux: f32 = 0;
if ((x > 0.0)) {
  aux = (x - f32(i32(x)));
} else {
  aux = (x + f32(i32(x)));
}
aux = cos((aux * PI));
var aux2: f32 = 0;
if ((aux < ((rnd(rs) * 2.0) - 1.0))) {
  if ((x > 0)) {
    aux2 = -width2;
  } else {
    aux2 = width2;
  }
}
v.x += ((t.x * ${w}) + aux2);
v.y += (${w} * t.y);
}`,
  },
  "circular": {
    params: [{ name: "angle", def: 90 }, { name: "seed", def: 0 }],
    verified: false, priority: 0, flags: [], types: ["2D"],
    code: (w, p) => `{
var c_a: f32 = ((${p[0]} * PI) / 180.0);
var aux: f32 = (sin((((t.x * 12.9898) + (t.y * 78.233)) + ${p[1]})) * 43758.5453);
aux = (aux - f32(i32(aux)));
var rnd_: f32 = (((2 * (rnd(rs) + aux)) - 2.0) * c_a);
var rad: f32 = sqrt(((t.x * t.x) + (t.y * t.y)));
var ang: f32 = atan2(t.y, t.x);
var by: f32 = sin((ang + rnd_));
var bx: f32 = cos((ang + rnd_));
v.x += (${w} * (bx * rad));
v.y += (${w} * (by * rad));
}`,
  },
  "circular2": {
    params: [{ name: "angle", def: 90 }, { name: "seed", def: 0 }, { name: "xx", def: 12.9898 }, { name: "yy", def: 78.233 }],
    verified: false, priority: 0, flags: [], types: ["2D"],
    code: (w, p) => `{
var c_a: f32 = ((${p[0]} * PI) / 180.0);
var aux: f32 = (sin((((t.x * ${p[2]}) + (t.y * ${p[3]})) + ${p[1]})) * 43758.5453);
aux = (aux - f32(i32(aux)));
var rnd_: f32 = (((2 * (rnd(rs) + aux)) - 2.0) * c_a);
var rad: f32 = sqrt(((t.x * t.x) + (t.y * t.y)));
var ang: f32 = atan2(t.y, t.x);
var by: f32 = sin((ang + rnd_));
var bx: f32 = cos((ang + rnd_));
v.x += (${w} * (bx * rad));
v.y += (${w} * (by * rad));
}`,
  },
  "minkQM": {
    params: [{ name: "a", def: 1 }, { name: "b", def: 1 }, { name: "c", def: 1 }, { name: "dd", def: 1 }, { name: "e", def: 0.5 }, { name: "f", def: 20 }],
    verified: false, priority: 0, flags: [], types: ["2D"],
    funcNames: ["minkQM_minkowski"],
    funcs: `fn minkQM_minkowski(x: f32, a: f32, b: f32, c: f32, dd: f32, e: f32, f: f32) -> f32 {
  var p_: f32 = 0;
  var q: f32 = a;
  var r_: f32 = (p_ + b);
  var s: f32 = c;
  var m: f32 = 0.0;
  var n: f32 = 0.0;
  var d: f32 = dd;
  var y: f32 = p_;
  for (var it: i32 = 0; (f32(it) < f); it++) {
    d = (d * e);
    m = (p_ + r_);
    n = (q + s);
    if ((x < (m / n))) {
      r_ = m;
      s = n;
    } else {
      y += d;
      p_ = m;
      q = n;
    }
  }
  return (y + d);
}`,
    code: (w, p) => `{
var mnkX: f32 = t.x;
var mnkY: f32 = t.y;
var is: i32 = 0;
if ((mnkX < 0)) {
  mnkX = -mnkX;
  is = 1;
}
if (((mnkX > 0.0) && (mnkX < 1.0))) {
  mnkX = minkQM_minkowski(mnkX, ${p[0]}, ${p[1]}, ${p[2]}, ${p[3]}, ${p[4]}, min(max(${p[5]}, 1.0), 50.0));
}
if ((is == 1)) {
  mnkX = -mnkX;
  is = 0;
}
if ((mnkY < 0)) {
  mnkY = -mnkY;
  is = 1;
}
if (((mnkY > 0.0) && (mnkY < 1.0))) {
  mnkY = minkQM_minkowski(mnkY, ${p[0]}, ${p[1]}, ${p[2]}, ${p[3]}, ${p[4]}, min(max(${p[5]}, 1.0), 50.0));
}
if ((is == 1)) {
  mnkY = -mnkY;
}
v.x += (${w} * mnkX);
v.y += (${w} * mnkY);
}`,
  },
  "r_circleblur": {
    params: [{ name: "n", def: 1 }, { name: "seed", def: 0 }, { name: "dist", def: 0.5 }, { name: "min", def: 0.1 }, { name: "max", def: 1 }],
    verified: false, priority: 0, flags: [], types: ["BASE_SHAPE","BLUR"],
    funcNames: ["roundc"],
    funcs: `fn roundc(x: f32) -> f32 { return sign(x) * floor(abs(x) + 0.5); }`,
    code: (w, p) => `{
var rcn: f32 = abs(${p[0]});
var angle: f32 = atan2(t.y, t.x);
var rad: f32 = sqrt(((t.x * t.x) + (t.y * t.y)));
rad = (rad % rcn);
var by: f32 = sin((angle + rad));
var bx: f32 = cos((angle + rad));
by = roundc((by * rad));
bx = roundc((bx * rad));
var rad2: f32 = (sqrt(rnd(rs)) * 0.5);
var angle2: f32 = (rnd(rs) * (2.0 * PI));
var a1: f32 = (sin((((bx * 127.1) + (by * 311.7)) + ${p[1]})) * 43758.5453);
a1 = (a1 - trunc(a1));
var a2: f32 = (sin((((bx * 269.5) + (by * 183.3)) + ${p[1]})) * 43758.5453);
a2 = (a2 - trunc(a2));
var a3: f32 = (sin((((by * 12.9898) + (bx * 78.233)) + ${p[1]})) * 43758.5453);
a3 = (a3 - trunc(a3));
a3 = ((a3 * (${p[4]} - ${p[3]})) + ${p[3]});
rad2 *= a3;
by = ((by + (rad2 * sin(angle2))) + (a1 * ${p[2]}));
bx = ((bx + (rad2 * cos(angle2))) + (a2 * ${p[2]}));
v.x += (${w} * bx);
v.y += (${w} * by);
}`,
  },
  "cpow3_wf": {
    params: [{ name: "r", def: 1 }, { name: "a", def: 0.1 }, { name: "divisor", def: 1 }, { name: "spread", def: 1 }, { name: "discrete_spread", def: 1 }, { name: "spread2", def: 0 }, { name: "offset2", def: 1 }],
    verified: false, priority: 0, flags: [], types: ["2D"],
    code: (w, p) => `{
var c: f32;
var d: f32;
var half_c: f32;
var half_d: f32;
var ang: f32;
var inv_spread: f32;
var full_spread: f32;
ang = ((2.0 * PI) / ${p[2]});
c = ((${p[0]} * cos(((PI / 2) * ${p[1]}))) / ${p[2]});
d = ((${p[0]} * sin(((PI / 2) * ${p[1]}))) / ${p[2]});
half_c = (c / 2);
half_d = (d / 2);
inv_spread = (0.5 / ${p[3]});
full_spread = ((2 * PI) * ${p[3]});
var ai: f32 = ph;
var n: f32 = (rnd(rs) * ${p[3]});
if ((${p[4]} >= 1.0)) {
  n = f32(i32(n));
}
if ((ai < 0)) {
  n += 1.0;
}
ai += ((2 * PI) * n);
if ((cos((ai * inv_spread)) < ((rnd(rs) * 2.0) - 1.0))) {
  ai -= full_spread;
}
var lnr2: f32 = log(r2);
var ri: f32 = (${w} * exp(((half_c * lnr2) - (d * ai))));
var ang2: f32 = (((((c * ai) * half_d) * lnr2) * ang) * ((rnd(rs) * ${p[5]}) + ${p[6]}));
v.x += (ri * cos(ang2));
v.y += (ri * sin(ang2));
}`,
  },
  "harmonograph_js": {
    params: [{ name: "seed", def: 1234 }, { name: "time", def: 100 }, { name: "a1", def: 128 }, { name: "f1", def: 5 }, { name: "p1", def: 113 }, { name: "d1", def: 0.001301650295393377 }, { name: "a2", def: 0 }, { name: "f2", def: 3 }, { name: "p2", def: 33 }, { name: "d2", def: 0.0013211574142884402 }, { name: "a3", def: 49 }, { name: "f3", def: -4 }, { name: "p3", def: 57 }, { name: "d3", def: 0.001107815803330482 }, { name: "a4", def: 97 }, { name: "f4", def: 1 }, { name: "p4", def: 68 }, { name: "d4", def: 0.0011498156833428647 }],
    verified: false, priority: 0, flags: [], types: ["2D","BASE_SHAPE"],
    funcNames: ["harmonograph_js_mo"],
    funcs: `fn harmonograph_js_mo(t_: f32, a1: f32, f1: f32, p_1: f32, d1: f32, a2: f32, f2: f32, p_2: f32, d2: f32) -> f32 {
  var p1: f32 = ((p_1 * PI) / 180.0);
  var p2: f32 = ((p_2 * PI) / 180.0);
  return (((a1 * sin(((t_ * f1) + p1))) * exp(((-1 * d1) * t_))) + ((a2 * sin(((t_ * f2) + p2))) * exp(((-1 * d2) * t_))));
}`,
    code: (w, p) => `{
var x: f32;
var y: f32;
var t_: f32 = (rnd(rs) * ${p[1]});
x = (harmonograph_js_mo(t_, ${p[2]}, ${p[3]}, ${p[4]}, ${p[5]}, ${p[6]}, ${p[7]}, ${p[8]}, ${p[9]}) / 180);
y = (harmonograph_js_mo(t_, ${p[10]}, ${p[11]}, (${p[12]} + 90.0), ${p[13]}, ${p[14]}, ${p[15]}, (${p[16]} + 90.0), ${p[17]}) / 180);
v.x += (x * ${w});
v.y += (y * ${w});
}`,
  },
  "dc_gnarly": {
    params: [{ name: "mode", def: 1 }, { name: "scalex", def: 0.05 }, { name: "scaley", def: 0.05 }, { name: "freqx1", def: 3.5 }, { name: "freqy1", def: 3.5 }, { name: "freqx2", def: 2 }, { name: "freqy2", def: 2 }, { name: "freqx3", def: 5 }, { name: "freqy3", def: 5 }, { name: "dc", def: 1 }, { name: "color1", def: 5 }, { name: "color2", def: 5 }, { name: "fmag", def: 1 }, { name: "distort", def: 0 }, { name: "blur", def: 5 }, { name: "scale_z", def: 0 }, { name: "offset_z", def: 0 }, { name: "reset_z", def: 0 }],
    verified: false, priority: 0, flags: ["dc","z"], types: ["2D","DC"],
    funcNames: ["roundc","sqrf"],
    funcs: `fn roundc(x: f32) -> f32 { return sign(x) * floor(abs(x) + 0.5); }

fn sqrf(x: f32) -> f32 {
  return (x * x);
}`,
    code: (w, p) => `{
var x0: f32 = t.x;
var y0: f32 = t.y;
if ((${p[14]} > 0)) {
  var r_: f32 = ((rnd(rs) * 2) * PI);
  var sina: f32 = sin(r_);
  var cosa: f32 = cos(r_);
  r_ = (${p[14]} * ((((((rnd(rs) + rnd(rs)) + rnd(rs)) + rnd(rs)) + rnd(rs)) + rnd(rs)) - 3.0));
  x0 += (r_ * cosa);
  y0 += (r_ * sina);
} else if ((${p[14]} < 0)) {
  x0 += (((rnd(rs) * ${p[14]}) * 2.0) - ${p[14]});
  y0 += (((rnd(rs) * ${p[14]}) * 2.0) - ${p[14]});
}
var x1: f32;
var y1: f32;
switch i32(roundc(min(max(${p[0]}, 0.0), 8.0))) {
  case 1: {
    x1 = (cos(((${p[3]} * y0) + sin((${p[5]} * (y0 + sin((${p[7]} * y0))))))) * ${p[1]});
    y1 = (cos(((${p[4]} * x0) + sin((${p[6]} * (x0 + sin((${p[8]} * x0))))))) * ${p[2]});
  }
  case 2: {
    x1 = (sin(((${p[3]} * y0) + sin((${p[5]} * (y0 + cos((${p[7]} * y0))))))) * ${p[1]});
    y1 = (sin(((${p[4]} * x0) + sin((${p[6]} * (x0 + cos((${p[8]} * x0))))))) * ${p[2]});
  }
  case 3: {
    x1 = (cos(((${p[3]} * y0) + sin((${p[5]} * (x0 + sin((${p[7]} * y0))))))) * ${p[1]});
    y1 = (cos(((${p[4]} * x0) + sin((${p[6]} * (y0 + sin((${p[8]} * x0))))))) * ${p[2]});
  }
  case 4: {
    x1 = (sin(((${p[3]} * y0) + sin(sqrt(abs((${p[5]} * (y0 + cos((${p[7]} * y0))))))))) * ${p[1]});
    y1 = (sin(((${p[4]} * x0) + sin(sqrt(abs((${p[6]} * (x0 + cos((${p[8]} * x0))))))))) * ${p[2]});
  }
  case 5: {
    x1 = (cos(((${p[3]} * y0) + asinh((${p[5]} * (y0 + sin((${p[7]} * y0))))))) * ${p[1]});
    y1 = (cos(((${p[4]} * x0) + asinh((${p[6]} * (x0 + sin((${p[8]} * x0))))))) * ${p[2]});
  }
  case 6: {
    x1 = (cos(((${p[3]} * y0) + tan((${p[5]} * (y0 + sin((${p[7]} * y0))))))) * ${p[1]});
    y1 = (cos(((${p[4]} * x0) + tan((${p[6]} * (x0 + sin((${p[8]} * x0))))))) * ${p[2]});
  }
  case 7: {
    x1 = (sin(((${p[3]} * y0) + sin(sqrf((${p[5]} * (y0 + cos((${p[7]} * y0)))))))) * ${p[1]});
    y1 = (sin(((${p[4]} * x0) + sin(sqrf((${p[6]} * (x0 + cos((${p[8]} * x0)))))))) * ${p[2]});
  }
  case 8: {
    x1 = (sin(((${p[3]} * y0) + sin(sqrf((${p[5]} * (x0 + cos((${p[7]} * y0)))))))) * ${p[1]});
    y1 = (sin(((${p[4]} * x0) + sin(sqrf((${p[6]} * (y0 + cos((${p[8]} * x0)))))))) * ${p[2]});
  }
  case default: {
    x1 = (sin((${p[3]} * y0)) * ${p[1]});
    y1 = (sin((${p[4]} * x0)) * ${p[2]});
  }
}
var s1: f32 = (log(sqrt(((x1 * x1) + (y1 * y1)))) * ${p[13]});
v.x += ((${w} * (x0 + x1)) / 2);
v.y += ((${w} * (y0 + y1)) / 2);
if ((i32(roundc(min(max(${p[9]}, 0.0), 1.0))) != 0)) {
  (*cp) = (abs((cos(((x0 + (x1 * ${p[10]})) + s1)) + sin(((y0 + (y1 * ${p[11]})) + s1)))) % min(max(${p[12]}, 0.05), 1.0));
}
var dz: f32 = (((*cp) * ${p[15]}) + ${p[16]});
if ((i32(roundc(min(max(${p[17]}, 0.0), 1.0))) > 0)) {
  pz_ = dz;
} else {
  pz_ += dz;
}
}`,
  },
  "chrysanthemum": {
    params: [],
    verified: false, priority: 0, flags: [], types: ["BASE_SHAPE"],
    code: (w, _p) => `{
var u: f32 = ((21.0 * PI) * rnd(rs));
var p4: f32 = sin(((17.0 * u) / 3.0));
var p8: f32 = sin(((2.0 * cos((3.0 * u))) - (28.0 * u)));
var r_: f32 = ((5.0 * (1 + sin(((11.0 * u) / 5.0)))) - ((((((((((((4.0 * p4) * p4) * p4) * p4) * p8) * p8) * p8) * p8) * p8) * p8) * p8) * p8));
r_ *= ${w};
v.x += (r_ * cos(u));
v.y += (r_ * sin(u));
}`,
  },
  "starfractal": {
    params: [{ name: "m", def: 3 }],
    verified: false, priority: 0, flags: [], types: ["2D","SIMULATION","BASE_SHAPE"],
    code: (w, p) => `{
var a: array<f32, 25>;
var b: array<f32, 25>;
var x: f32 = 1;
var y: f32 = 1;
var x1: f32;
var y1: f32;
for (var i: i32 = 0; (f32(i) < min(max(${p[0]}, 3.0), 10.0)); i++) {
  a[(2 * i)] = cos((((2 * PI) * f32((i + 1))) / min(max(${p[0]}, 3.0), 10.0)));
  b[(2 * i)] = sin((((2 * PI) * f32((i + 1))) / min(max(${p[0]}, 3.0), 10.0)));
}
for (var i: i32 = 0; (f32(i) < min(max(${p[0]}, 3.0), 10.0)); i++) {
  a[((2 * i) + 1)] = (0.5 * (cos((((2 * PI) * f32((i + 1))) / min(max(${p[0]}, 3.0), 10.0))) + cos((((2 * PI) * f32(i)) / min(max(${p[0]}, 3.0), 10.0)))));
  b[((2 * i) + 1)] = (0.5 * (sin((((2 * PI) * f32((i + 1))) / min(max(${p[0]}, 3.0), 10.0))) + sin((((2 * PI) * f32(i)) / min(max(${p[0]}, 3.0), 10.0)))));
}
for (var k: i32 = 0; (k < 500); k++) {
  var c: i32 = i32((rnd(rs) * (2.0 * min(max(${p[0]}, 3.0), 10.0))));
  x1 = (((x / ((x * x) + (y * y))) / 3) + a[c]);
  y1 = (((-y / ((x * x) + (y * y))) / 3) + b[c]);
  x = (x1 / ((x1 * x1) + (y1 * y1)));
  y = (y1 / ((x1 * x1) + (y1 * y1)));
}
v.x = (x * ${w});
v.y = (y * ${w});
}`,
  },
  "swirl3D_wf": {
    params: [{ name: "n", def: 0 }],
    verified: false, priority: 0, flags: ["3d","dc","z"], types: ["3D","DC"],
    code: (w, p) => `{
var rad: f32 = r;
var ang: f32 = ph;
v.x += (${w} * (rad * cos(ang)));
v.y += (${w} * (rad * sin(ang)));
pz_ += (${w} * sin(((6.0 * cos(rad)) - (${p[0]} * ang))));
(*cp) = abs(sin(((6.0 * cos(rad)) - (${p[0]} * ang))));
}`,
  },
  "waves42": {
    params: [{ name: "scalex", def: 0.05 }, { name: "scaley", def: 0.05 }, { name: "freqx", def: 7 }, { name: "freqy", def: 13 }, { name: "cont", def: 0 }, { name: "yfact", def: 0.1 }, { name: "freqx2", def: 1 }],
    verified: false, priority: 0, flags: [], types: ["2D"],
    funcNames: ["roundc"],
    funcs: `fn roundc(x: f32) -> f32 { return sign(x) * floor(abs(x) + 0.5); }`,
    code: (w, p) => `{
var x0: f32 = t.x;
var y0: f32 = t.y;
var ax: f32 = floor((y0 * ${p[6]}));
ax = (sin(((((ax * 12.9898) + (ax * 78.233)) + 1.0) + ((y0 * 0.001) * ${p[5]}))) * 43758.5453);
ax = (ax - f32(i32(ax)));
if ((i32(roundc(min(max(${p[4]}, 0.0), 1.0))) == 1)) {
  ax = select(0.0, 1.0, (ax > 0.5));
}
v.x += (${w} * (x0 + (((sin((y0 * ${p[2]})) * ax) * ax) * ${p[0]})));
v.y += (${w} * (y0 + (sin((x0 * ${p[3]})) * ${p[1]})));
}`,
  },
  "waves4": {
    params: [{ name: "scalex", def: 0.05 }, { name: "scaley", def: 0.05 }, { name: "freqx", def: 7 }, { name: "freqy", def: 13 }, { name: "cont", def: 0 }, { name: "yfact", def: 0.1 }],
    verified: false, priority: 0, flags: [], types: ["2D"],
    funcNames: ["roundc"],
    funcs: `fn roundc(x: f32) -> f32 { return sign(x) * floor(abs(x) + 0.5); }`,
    code: (w, p) => `{
var x0: f32 = t.x;
var y0: f32 = t.y;
var ax: f32 = floor(((y0 * ${p[2]}) / (2.0 * PI)));
ax = (sin(((((ax * 12.9898) + (ax * 78.233)) + 1.0) + ((y0 * 0.001) * ${p[5]}))) * 43758.5453);
ax = (ax - f32(i32(ax)));
if ((i32(roundc(min(max(${p[4]}, 0.0), 1.0))) == 1)) {
  ax = select(0.0, 1.0, (ax > 0.5));
}
v.x += (${w} * (x0 + (((sin((y0 * ${p[2]})) * ax) * ax) * ${p[0]})));
v.y += (${w} * (y0 + (sin((x0 * ${p[3]})) * ${p[1]})));
}`,
  },
  "cut_fingerprint": {
    params: [{ name: "seed", def: 10000 }, { name: "mode", def: 1 }, { name: "zoom", def: 20 }, { name: "width", def: 0.8 }, { name: "invert", def: 0 }],
    verified: false, priority: 0, flags: ["hide"], types: ["BASE_SHAPE","SIMULATION"],
    funcNames: ["cut_fingerprint_hash2","cut_fingerprint_getRGBColor"],
    funcs: `fn cut_fingerprint_hash2(p__in: vec2f) -> vec2f {
  var p_: vec2f = p__in;
  p_ = vec2f(dot(p_, vec2f(63.31, 127.63)), dot(p_, vec2f(395.467, 213.799)));
  return ((fract((sin(p_) * vec2f(43141.59265))) * vec2f(2.0)) - vec2f(1.0));
}

fn cut_fingerprint_getRGBColor(uv_in: vec2f, seed: f32, width: f32) -> vec3f {
  var uv: vec2f = uv_in;
  var color: vec3f = vec3f(0.0, 0.0, 0.0);
  var bounds: f32 = smoothstep(9.0, 10.0, length((uv * vec2f(0.7, 0.5))));
  var a: f32 = 0.0;
  var h: vec2f = vec2f(floor((7.0 * seed)), 0.0);
  for (var i: i32 = 0; (i < 50); i++) {
    var s: f32 = sign(h.x);
    h = (cut_fingerprint_hash2(h) * vec2f(15.0, 20.0));
    a += (s * atan2((uv.x - h.x), (uv.y - h.y)));
  }
  uv = (uv + abs(cut_fingerprint_hash2(h)));
  a += atan2(uv.y, uv.x);
  var p_: f32 = ((1.0 - bounds) * width);
  var s: f32 = min(0.3, p_);
  var l: f32 = (length(uv) + (0.319 * a));
  var m: f32 = mmod(l, 2.0);
  var v_: f32 = ((1.0 - smoothstep((2.0 - s), 2.0, m)) * smoothstep(p_, (p_ + s), m));
  return vec3f(v_, v_, v_);
}`,
    code: (w, p) => `{
var x: f32;
var y: f32;
var px_center: f32;
var py_center: f32;
var color: vec3f = vec3f(1.0, 1.0, 0.0);
if ((min(max(${p[1]}, 0.0), 1.0) == 0.0)) {
  x = t.x;
  y = t.y;
  px_center = 0.0;
  py_center = 0.0;
} else {
  x = (rnd(rs) - 0.5);
  y = (rnd(rs) - 0.5);
  px_center = 0.0;
  py_center = 0.0;
}
var uv: vec2f = (vec2f(x, y) * vec2f(min(max(${p[2]}, 1.0), 100.0)));
color = cut_fingerprint_getRGBColor(uv, ${p[0]}, min(max(${p[3]}, 0.02), 1.0));
(*hd) = false;
if ((min(max(${p[4]}, 0.0), 1.0) == 0)) {
  if ((color.x == 0.0)) {
    v.x = 0.0;
    v.y = 0.0;
    (*hd) = true;
  }
} else {
  if ((color.x > 0.0)) {
    v.x = 0.0;
    v.y = 0.0;
    (*hd) = true;
  }
}
v.x = (${w} * (x - px_center));
v.y = (${w} * (y - py_center));
}`,
  },
  "cut_glypho": {
    params: [{ name: "mode", def: 1 }, { name: "zoom", def: 1 }, { name: "invert", def: 0 }, { name: "f1", def: 0.115 }, { name: "f2", def: 0.75 }, { name: "f3", def: 1.5 }],
    verified: false, priority: 0, flags: ["hide"], types: ["2D","BASE_SHAPE","SIMULATION"],
    code: (w, p) => `{
var x: f32;
var y: f32;
var px_center: f32;
var py_center: f32;
if ((min(max(${p[0]}, 0.0), 1.0) == 0)) {
  x = t.x;
  y = t.y;
  px_center = 0.0;
  py_center = 0.0;
} else {
  x = (rnd(rs) - 0.5);
  y = (rnd(rs) - 0.5);
  px_center = 0.0;
  py_center = 0.0;
}
var uv: vec2f = (vec2f(x, y) * vec2f(min(max(${p[1]}, 0.1), 50.0)));
var color: f32 = 0.0;
var m: f32 = 0.0;
var stp: f32 = (PI / 5.0);
for (var n: f32 = 1.0; (n < 2.5); n += 0.5) {
  for (var i: f32 = 0.0001; (i < (2.0 * PI)); i += stp) {
    var uvi: vec2f = ((uv * vec2f(n)) + vec2f((cos((i + ((n * stp) * 0.5))) * 0.4), (sin((i + ((n * stp) * 0.5))) * 0.4)));
    var l: f32 = length(uvi);
    m += (smoothstep((${p[3]} * n), 0.0, l) * ${p[5]});
  }
}
m = step(${p[4]}, fract((m * ${p[5]})));
color = m;
(*hd) = false;
if ((min(max(${p[2]}, 0.0), 1.0) == 0)) {
  if ((color == 0.0)) {
    v.x = 0;
    v.y = 0;
    (*hd) = true;
  }
} else {
  if ((color > 0.0)) {
    v.x = 0;
    v.y = 0;
    (*hd) = true;
  }
}
v.x = (${w} * (x - px_center));
v.y = (${w} * (y - py_center));
}`,
  },
  "cut_kaleido": {
    params: [{ name: "seed", def: 1000 }, { name: "mode", def: 1 }, { name: "time", def: 0 }, { name: "n", def: 6 }, { name: "zoom", def: 0.5 }, { name: "invert", def: 0 }],
    verified: false, priority: 0, flags: ["hide"], types: ["2D","BASE_SHAPE","SIMULATION"],
    funcNames: ["cut_kaleido_distToColor"],
    funcs: `fn cut_kaleido_distToColor(d: f32) -> f32 {
  return (0.0 - cos((d * 13.0)));
}`,
    code: (w, p) => `{
var x: f32;
var y: f32;
var ci: array<vec2f, 20>;
if ((min(max(${p[1]}, 0.0), 1.0) == 0)) {
  x = t.x;
  y = t.y;
} else {
  x = (rnd(rs) - 0.5);
  y = (rnd(rs) - 0.5);
}
var uv: vec2f = vec2f((x * ${p[4]}), (y * ${p[4]}));
for (var i: i32 = 0; (f32(i) < min(max(${p[3]}, 2.0), 20.0)); i++) {
  var fi: f32 = (((2.0 * 3.14) * (f32(i) + (0.02 * ${p[2]}))) / min(max(${p[3]}, 2.0), 20.0));
  ci[i] = vec2f((0.5 * sin(fi)), (0.5 * cos(fi)));
}
var d: f32 = 1.0;
var k: f32 = (100.0 + (10.0 * sin((${p[2]} / 5.0))));
for (var i: i32 = 0; (f32(i) < min(max(${p[3]}, 2.0), 20.0)); i++) {
  d = (vec2f(d) + sin((vec2f(k) * distance(uv, ci[i]))));
}
var color: f32 = cut_kaleido_distToColor((d / min(max(${p[3]}, 2.0), 20.0)));
(*hd) = false;
if ((min(max(${p[5]}, 0.0), 1.0) == 0)) {
  if ((color > 0.0)) {
    x = 0;
    y = 0;
    (*hd) = true;
  }
} else {
  if ((color <= 0.0)) {
    x = 0;
    y = 0;
    (*hd) = true;
  }
}
v.x = (${w} * x);
v.y = (${w} * y);
}`,
  },
  "cut_triantess": {
    params: [{ name: "mode", def: 1 }, { name: "Iters", def: 20 }, { name: "SRadius", def: 0.01 }, { name: "pParam", def: 3 }, { name: "qParam", def: 3 }, { name: "rParam", def: 4 }, { name: "uBaryc", def: 1 }, { name: "vBaryc", def: 1 }, { name: "wBaryc", def: 0 }, { name: "zoom", def: 2 }, { name: "invert", def: 0 }],
    verified: false, priority: 0, flags: ["hide"], types: ["2D","BASE_SHAPE","SIMULATION"],
    funcNames: ["Mat2","cut_triantess_hdott","hlengtht","cut_triantess_hnormalizet","cut_triantess_hdots","Mat2_Init","times","cut_triantess_hlengths","cut_triantess_DD","cut_triantess_dist2Segment","cut_triantess_dist2Segments"],
    funcs: `struct Mat2 {
  a00: f32,
  a01: f32,
  a10: f32,
  a11: f32,
}

fn cut_triantess_hdott(a: vec3f, b: vec3f, spaceType: f32) -> f32 {
  return ((dot(vec2f(a.x, a.y), vec2f(b.x, b.y)) * spaceType) + (a.z * b.z));
}

fn hlengtht(v_: vec3f, spaceType: f32) -> f32 {
  return sqrt(abs(cut_triantess_hdott(v_, v_, spaceType)));
}

fn cut_triantess_hnormalizet(v_: vec3f, spaceType: f32) -> vec3f {
  var l: f32 = (1.0 / hlengtht(v_, spaceType));
  return (v_ * vec3f(l));
}

fn cut_triantess_hdots(a: vec3f, b: vec3f, spaceType: f32) -> f32 {
  return (dot(vec2f(a.x, a.y), vec2f(b.x, b.y)) + ((spaceType * a.z) * b.z));
}

fn Mat2_Init(m: ptr<function, Mat2>, v00: f32, v10: f32, v01: f32, v11: f32) {
  (*m).a00 = v00;
  (*m).a01 = v01;
  (*m).a10 = v10;
  (*m).a11 = v11;
}

fn times(m: ptr<function, Mat2>, v_: vec2f) -> vec2f {
  return vec2f((((*m).a00 * v_.x) + ((*m).a01 * v_.y)), (((*m).a10 * v_.x) + ((*m).a11 * v_.y)));
}

fn cut_triantess_hlengths(v_: vec3f, spaceType: f32) -> f32 {
  return sqrt(abs(cut_triantess_hdots(v_, v_, spaceType)));
}

fn cut_triantess_DD(tha: f32, r_: f32, spaceType: f32) -> f32 {
  return ((tha * (1.0 + ((spaceType * r_) * r_))) / (1.0 + (((spaceType * spaceType) * r_) * tha)));
}

fn cut_triantess_dist2Segment(z: vec3f, n: vec3f, r_: f32, p_: vec3f, SRadius: f32, spaceType: f32) -> f32 {
  var smat: Mat2;
  var v1: vec2f = vec2f(1.0, -(cut_triantess_hdots(p_, n, spaceType)));
  var v2: vec2f = vec2f(-(cut_triantess_hdott(p_, n, spaceType)), 1.0);
  Mat2_Init(&(smat), v1.x, v1.y, v2.x, v2.y);
  var w1: f32 = cut_triantess_hdott(z, p_, spaceType);
  var w2: f32 = cut_triantess_hdots(z, n, spaceType);
  var v_: vec2f = times(&(smat), vec2f(w1, w2));
  v_.y = min(0.0, v_.y);
  var pmin: vec3f = cut_triantess_hnormalizet(((p_ * vec3f(v_.x)) + (n * vec3f(v_.y))), spaceType);
  var tha: f32 = (cut_triantess_hlengths((pmin - z), spaceType) / hlengtht((pmin + z), spaceType));
  return cut_triantess_DD(((tha - SRadius) / (1.0 + ((spaceType * tha) * SRadius))), r_, spaceType);
}

fn cut_triantess_dist2Segments(z: vec3f, r_: f32, nb: vec3f, nc: vec3f, spaceType: f32, p_: vec3f, SRadius: f32) -> f32 {
  var da: f32 = cut_triantess_dist2Segment(z, vec3f(1.0, 0.0, 0.0), r_, p_, SRadius, spaceType);
  var db: f32 = cut_triantess_dist2Segment(z, nb, r_, p_, SRadius, spaceType);
  var dc: f32 = cut_triantess_dist2Segment(z, (nc * vec3f(1.0, 1.0, spaceType)), r_, p_, SRadius, spaceType);
  return min(min(da, db), dc);
}`,
    code: (w, p) => `{
var x: f32;
var y: f32;
var SRadius: f32 = 0.01;
var pParam: i32 = 3;
var qParam: i32 = 3;
var rParam: i32 = 4;
var U: f32 = min(max(${p[6]}, 0.0), 1.0);
var V: f32 = min(max(${p[7]}, 0.0), 1.0);
var W: f32 = min(max(${p[8]}, 0.0), 1.0);
var nb: vec3f;
var nc: vec3f;
var p_: vec3f;
var q: vec3f;
var pA: vec3f;
var pB: vec3f;
var pC: vec3f;
var spaceType: f32 = 0.0;
var aaScale: f32 = 0.0005;
var backGroundColor: f32 = 1.0;
var segColor: f32 = 0.0;
if ((min(max(${p[0]}, 0.0), 1.0) == 0)) {
  x = t.x;
  y = t.y;
} else {
  x = (rnd(rs) - 0.5);
  y = (rnd(rs) - 0.5);
}
var uv: vec2f = vec2f((x * ${p[9]}), (y * ${p[9]}));
spaceType = sign(((((min(max(${p[4]}, 1.0), 12.0) * min(max(${p[5]}, 1.0), 12.0)) + (min(max(${p[3]}, 1.0), 12.0) * min(max(${p[5]}, 1.0), 12.0))) + (min(max(${p[3]}, 1.0), 12.0) * min(max(${p[4]}, 1.0), 12.0))) - ((min(max(${p[3]}, 1.0), 12.0) * min(max(${p[4]}, 1.0), 12.0)) * min(max(${p[5]}, 1.0), 12.0))));
var cospip: f32 = cos((PI / min(max(${p[3]}, 1.0), 12.0)));
var sinpip: f32 = sin((PI / min(max(${p[3]}, 1.0), 12.0)));
var cospiq: f32 = cos((PI / min(max(${p[4]}, 1.0), 12.0)));
var sinpiq: f32 = sin((PI / min(max(${p[4]}, 1.0), 12.0)));
var cospir: f32 = cos((PI / min(max(${p[5]}, 1.0), 12.0)));
var sinpir: f32 = sin((PI / min(max(${p[5]}, 1.0), 12.0)));
var ncsincos: f32 = ((cospiq + (cospip * cospir)) / sinpip);
nb = vec3f(-cospip, sinpip, 0.0);
nc = vec3f(-cospir, -ncsincos, sqrt(abs(((ncsincos + sinpir) * (-ncsincos + sinpir)))));
if ((spaceType == 0.0)) {
  nc.z = 0.25;
}
pA = vec3f((nb.y * nc.z), (-nb.x * nc.z), ((nb.x * nc.y) - (nb.y * nc.x)));
pB = vec3f(0.0, nc.z, -nc.y);
pC = vec3f(0.0, 0.0, nb.y);
q = (((pA * vec3f(U)) + (pB * vec3f(V))) + (pC * vec3f(W)));
p_ = cut_triantess_hnormalizet(q, spaceType);
var color: f32 = backGroundColor;
var r_: f32 = length(uv);
var z3: vec3f = (vec3f((uv.x * 2.0), (uv.y * 2.0), (1.0 - ((spaceType * r_) * r_))) * vec3f((1.0 / (1.0 + ((spaceType * r_) * r_)))));
if (((spaceType == -1.0) && (r_ >= 1.0))) {
  color = backGroundColor;
}
for (var i: i32 = 0; (f32(i) < min(max(${p[1]}, 0.0), 20.0)); i++) {
  z3.x = abs(z3.x);
  var t_: f32 = (-2.0 * min(0.0, dot(nb, z3)));
  z3 = (z3 + ((nb * vec3f(1.0, 1.0, spaceType)) * vec3f(t_)));
  t_ = (-2.0 * min(0.0, dot(nc, z3)));
  z3 = (z3 + ((nc * vec3f(1.0, 1.0, spaceType)) * vec3f(t_)));
}
var ds: f32 = cut_triantess_dist2Segments(z3, r_, nb, nc, spaceType, p_, min(max(${p[2]}, 0.001), 0.1));
color = mix(segColor, color, smoothstep(-1.0, 1.0, ((ds * 0.5) / aaScale)));
if ((spaceType == -1.0)) {
  color = mix(backGroundColor, color, smoothstep(0.0, 1.0, (((1.0 - r_) * 0.5) / aaScale)));
}
(*hd) = false;
if ((min(max(${p[10]}, 0.0), 1.0) == 0)) {
  if ((color > 0.0)) {
    x = 0;
    y = 0;
    (*hd) = true;
  }
} else {
  if ((color <= 0.0)) {
    x = 0;
    y = 0;
    (*hd) = true;
  }
}
v.x = (${w} * x);
v.y = (${w} * y);
}`,
  },
  "cut_truchetweaving": {
    params: [{ name: "randomize", def: 0 }, { name: "mode", def: 1 }, { name: "type", def: 0 }, { name: "width", def: 0.15 }, { name: "zoom", def: 8 }, { name: "invert", def: 0 }],
    verified: false, priority: 0, flags: ["hide"], types: ["2D","BASE_SHAPE","SIMULATION"],
    funcNames: ["Mat2","mmod2","cut_truchetweaving_N21","Mat2_Init","times","cut_truchetweaving_UvCirc","cut_truchetweaving_UvBeam","cut_truchetweaving_Truchet"],
    funcs: `struct Mat2 {
  a00: f32,
  a01: f32,
  a10: f32,
  a11: f32,
}

fn mmod2(a: vec2f, b: vec2f) -> vec2f { return a - b * floor(a / b); }

fn cut_truchetweaving_N21(id: vec2f) -> f32 {
  return fract((sin(((id.x * 324.23) + (id.y * 5604.342))) * 87654.53));
}

fn Mat2_Init(m: ptr<function, Mat2>, v00: f32, v10: f32, v01: f32, v11: f32) {
  (*m).a00 = v00;
  (*m).a01 = v01;
  (*m).a10 = v10;
  (*m).a11 = v11;
}

fn times(m: ptr<function, Mat2>, v_: vec2f) -> vec2f {
  return vec2f((((*m).a00 * v_.x) + ((*m).a01 * v_.y)), (((*m).a10 * v_.x) + ((*m).a11 * v_.y)));
}

fn cut_truchetweaving_UvCirc(uv: vec2f, radius: f32, thickness: f32) -> vec4f {
  var st: vec2f = vec2f(atan2(uv.x, uv.y), length(uv));
  var t_: f32 = (thickness / 2.0);
  var w_: f32 = 0.01;
  var r1: f32 = (radius - t_);
  var r2_: f32 = (radius + t_);
  var mask: f32 = smoothstep((t_ + w_), t_, abs((radius - st.y)));
  var alpha: f32 = smoothstep((t_ + 0.1), t_, abs((radius - st.y)));
  alpha = ((alpha * alpha) * mix(0.5, 1.0, mask));
  return vec4f((st.x * radius), st.y, mask, alpha);
}

fn cut_truchetweaving_UvBeam(uv: vec2f, thickness: f32) -> vec4f {
  var t_: f32 = (thickness / 2.0);
  var w_: f32 = 0.01;
  var mask: f32 = smoothstep((t_ + w_), t_, abs(uv.y));
  var alpha: f32 = smoothstep((t_ + 0.1), t_, abs(uv.y));
  alpha = ((alpha * alpha) * (0.5 + (0.5 * mask)));
  return vec4f(uv.x, uv.y, mask, alpha);
}

fn cut_truchetweaving_Truchet(uv_in: vec2f, n: f32, u: vec2f, type_: i32, width: f32) -> vec3f {
  var uv: vec2f = uv_in;
  var I3: f32 = 0.333333333;
  var I6: f32 = 0.166666666;
  var R3: f32 = 1.732050807;
  var IR3: f32 = 0.577350269;
  var HIR3: f32 = 0.288675134;
  var S60: f32 = 0.866025404;
  var C60: f32 = 0.5;
  var CURVE_WIDTH: f32 = width;
  var W111: f32 = 0.1;
  var W113: f32 = 0.2;
  var W122: f32 = 0.4;
  var W223: f32 = 0.8;
  var W333: f32 = 1.0;
  if ((type_ == 1)) {
    CURVE_WIDTH = mix(0.05, 0.25, (((sin((u.x + sin(u.y))) + sin((u.y * 0.35))) * 0.25) + 0.5));
  }
  uv = (uv - vec2f(0.5));
  uv.x /= R3;
  var v1: vec4f = vec4f(0.0, 0.0, 0.0, 0.0);
  var v2: vec4f = vec4f(0.0, 0.0, 0.0, 0.0);
  var v3: vec4f = vec4f(0.0, 0.0, 0.0, 0.0);
  var w_: f32 = 0.15;
  var r_: f32 = (floor((fract((n * 5.0)) * 6.0)) / 6.0);
  r_ *= 6.28;
  var s: f32 = sin(r_);
  var c: f32 = cos(r_);
  var rot: Mat2;
  Mat2_Init(&(rot), c, -s, s, c);
  uv = times(&(rot), uv);
  if ((n < W111)) {
    v1 = cut_truchetweaving_UvCirc((uv - vec2f(0.0, I3)), I6, CURVE_WIDTH);
    v2 = cut_truchetweaving_UvCirc((uv - vec2f(HIR3, -I6)), I6, CURVE_WIDTH);
    v3 = cut_truchetweaving_UvCirc((uv - vec2f(-HIR3, -I6)), I6, CURVE_WIDTH);
  } else if ((n < W113)) {
    v1 = cut_truchetweaving_UvCirc((uv - vec2f(0.0, I3)), I6, CURVE_WIDTH);
    v2 = cut_truchetweaving_UvCirc((uv - vec2f(0.0, -I3)), I6, CURVE_WIDTH);
    v3 = cut_truchetweaving_UvBeam(uv, CURVE_WIDTH);
  } else if ((n < W122)) {
    v1 = cut_truchetweaving_UvCirc((uv - vec2f(-HIR3, -I6)), I6, CURVE_WIDTH);
    v2 = cut_truchetweaving_UvCirc((uv - vec2f(IR3, 0.0)), 0.5, CURVE_WIDTH);
    v3 = cut_truchetweaving_UvCirc((uv - vec2f(HIR3, 0.5)), 0.5, CURVE_WIDTH);
  } else if ((n < W223)) {
    v1 = cut_truchetweaving_UvCirc((uv - vec2f(IR3, 0.0)), 0.5, CURVE_WIDTH);
    v2 = cut_truchetweaving_UvCirc((uv - vec2f(-IR3, 0.0)), 0.5, CURVE_WIDTH);
    v3 = cut_truchetweaving_UvBeam(uv, CURVE_WIDTH);
  } else {
    var rot60: Mat2;
    var rot60i: Mat2;
    Mat2_Init(&(rot60), C60, -S60, S60, C60);
    Mat2_Init(&(rot60i), C60, S60, -S60, C60);
    v1 = cut_truchetweaving_UvBeam(uv, CURVE_WIDTH);
    v2 = cut_truchetweaving_UvBeam(times(&(rot60), uv), CURVE_WIDTH);
    v3 = cut_truchetweaving_UvBeam(times(&(rot60i), uv), CURVE_WIDTH);
  }
  var d1: f32 = fract((n * 10.0));
  var v_: vec4f;
  if ((d1 < 0.166)) {
    v_ = mix(v1, mix(v2, v3, v3.w), max(v2.w, v3.w));
  }
  if ((d1 < 0.333)) {
    v_ = mix(v1, mix(v3, v2, v2.w), max(v2.w, v3.w));
  } else if ((d1 < 0.5)) {
    v_ = mix(v2, mix(v1, v3, v3.w), max(v1.w, v3.w));
  } else if ((d1 < 0.666)) {
    v_ = mix(v2, mix(v3, v1, v1.w), max(v1.w, v3.w));
  } else if ((d1 < 0.833)) {
    v_ = mix(v3, mix(v1, v2, v2.w), max(v1.w, v2.w));
  } else {
    v_ = mix(v3, mix(v2, v1, v1.w), max(v1.w, v2.w));
  }
  return vec3f(v_.z, v_.z, v_.z);
}`,
    code: (w, p) => `{
var x: f32;
var y: f32;
if ((min(max(${p[1]}, 0.0), 1.0) == 0)) {
  x = t.x;
  y = t.y;
} else {
  x = (rnd(rs) - 0.5);
  y = (rnd(rs) - 0.5);
}
var uvx: f32 = (${p[0]} * sin(((${p[0]} * 180.0) / PI)));
var u: vec2f = vec2f(((x * min(max(${p[4]}, 0.1), 50.0)) - uvx), ((y * min(max(${p[4]}, 0.1), 50.0)) - uvx));
var R3: f32 = 1.732050807;
var s: vec2f = vec2f(1.0, R3);
var a: vec2f = ((mmod2(u, s) * vec2f(2.0)) - s);
var b: vec2f = ((mmod2((u + (s * vec2f(0.5))), s) * vec2f(2.0)) - s);
u = (u / s);
var da: f32 = dot(a, a);
var db: f32 = dot(b, b);
var id: vec2f;
if ((da < db)) {
  id = floor(u);
} else {
  u = (u + vec2f(0.5));
  id = (floor(u) - vec2f(0.5));
}
var n: f32 = cut_truchetweaving_N21(id);
var O: vec3f = cut_truchetweaving_Truchet(fract(u), n, u, i32(min(max(${p[2]}, 0.0), 1.0)), min(max(${p[3]}, 0.0), 0.25));
var col: f32 = 0.0;
col = O.z;
(*hd) = false;
if ((min(max(${p[5]}, 0.0), 1.0) == 0)) {
  if ((col > 0.0)) {
    x = 0.0;
    y = 0.0;
    (*hd) = true;
  }
} else {
  if ((col <= 0.0)) {
    x = 0.0;
    y = 0.0;
    (*hd) = true;
  }
}
v.x = (${w} * x);
v.y = (${w} * y);
}`,
  },
  "cut_hextruchetflow": {
    params: [{ name: "randomize", def: 0 }, { name: "mode", def: 1 }, { name: "grid", def: 0 }, { name: "zoom", def: 10 }, { name: "invert", def: 0 }],
    verified: false, priority: 0, flags: ["hide"], types: ["2D","BASE_SHAPE","SIMULATION"],
    funcNames: ["cut_hextruchetflow_PixToHex","cut_hextruchetflow_HexToPix","cut_hextruchetflow_Hashfv2","cut_hextruchetflow_HexEdgeDist","cut_hextruchetflow_ShowScene"],
    funcs: `fn cut_hextruchetflow_PixToHex(p_: vec2f) -> vec2f {
  var sqrt3: f32 = 1.73205;
  var c: vec3f = vec3f(0.0, 0.0, 0.0);
  var r_: vec3f;
  var dr: vec3f;
  var t0: vec2f = vec2f((((1.0 / sqrt3) * p_.x) - ((1.0 / 3.0) * p_.y)), ((2.0 / 3.0) * p_.y));
  c.x = t0.x;
  c.z = t0.y;
  c.y = (-c.x - c.z);
  r_ = floor((c + vec3f(0.5)));
  dr = abs((r_ - c));
  var t1: vec3f = vec3f(dr.y, dr.z, dr.x);
  var t2: vec3f = vec3f(dr.z, dr.x, dr.y);
  r_ = (r_ - ((step(t1, dr) * step(t2, dr)) * vec3f(dot(r_, vec3f(1.0, 1.0, 1.0)))));
  return vec2f(r_.x, r_.z);
}

fn cut_hextruchetflow_HexToPix(h: vec2f) -> vec2f {
  var sqrt3: f32 = 1.73205;
  return vec2f((sqrt3 * (h.x + (0.5 * h.y))), (1.5 * h.y));
}

fn cut_hextruchetflow_Hashfv2(p_: vec2f) -> f32 {
  return fract((sin(dot(p_, vec2f(37.0, 39.0))) * 43758.54));
}

fn cut_hextruchetflow_HexEdgeDist(p__in: vec2f) -> f32 {
  var p_: vec2f = p__in;
  var sqrt3: f32 = 1.73205;
  p_ = abs(p_);
  return (((sqrt3 / 2.0) - p_.x) + (0.5 * min((p_.x - (sqrt3 * p_.y)), 0.0)));
}

fn cut_hextruchetflow_ShowScene(p_: vec2f, grid: i32) -> vec3f {
  var sqrt3: f32 = 1.73205;
  var col: vec3f = vec3f(0.0, 0.0, 0.0);
  var w_: vec3f = vec3f(0.0, 0.0, 0.0);
  var cId: vec2f;
  var pc: vec2f;
  var q: vec2f;
  var dir: f32;
  var a: f32;
  var d: f32;
  cId = cut_hextruchetflow_PixToHex(p_);
  pc = cut_hextruchetflow_HexToPix(cId);
  dir = ((2.0 * step(cut_hextruchetflow_Hashfv2(cId), 0.5)) - 1.0);
  var t0: vec2f = (pc + vec2f(0.0, -dir));
  w_.x = t0.x;
  w_.y = t0.y;
  w_.z = dot((vec2f(w_.x, w_.y) - p_), (vec2f(w_.x, w_.y) - p_));
  q = (pc + vec2f((sqrt3 / 2.0), (0.5 * dir)));
  d = dot((q - p_), (q - p_));
  if ((d < w_.z)) {
    w_ = vec3f(q.x, q.y, d);
  }
  q = (pc + vec2f((-sqrt3 / 2.0), (0.5 * dir)));
  d = dot((q - p_), (q - p_));
  if ((d < w_.z)) {
    w_ = vec3f(q.x, q.y, d);
  }
  w_.z = abs((sqrt(w_.z) - 0.5));
  d = cut_hextruchetflow_HexEdgeDist((p_ - pc));
  if ((grid == 1)) {
    col = (vec3f(1.0, 1.0, 1.0) * vec3f(mix(1.0, smoothstep(1.0, 1.0, d), smoothstep(0.01, 0.02, d))));
  }
  if ((w_.z < 0.25)) {
    col = vec3f(1.0, 1.0, 1.0);
  }
  return col;
}`,
    code: (w, p) => `{
var x: f32;
var y: f32;
if ((min(max(${p[1]}, 0.0), 1.0) == 0)) {
  x = t.x;
  y = t.y;
} else {
  x = (rnd(rs) - 0.5);
  y = (rnd(rs) - 0.5);
}
var shiftxy: f32 = (${p[0]} * sin(((${p[0]} * 180.0) / PI)));
var uv: vec2f = ((vec2f(x, y) * vec2f(min(max(${p[3]}, 0.1), 50.0))) - vec2f(shiftxy, shiftxy));
var color: vec3f = vec3f(0.0, 0.0, 0.0);
color = (color + cut_hextruchetflow_ShowScene((uv + vec2f(step(1.5, 1.0))), i32(min(max(${p[2]}, 0.0), 1.0))));
(*hd) = false;
if ((min(max(${p[4]}, 0.0), 1.0) == 0)) {
  if ((color.x > 0.9)) {
    x = 0.0;
    y = 0.0;
    (*hd) = true;
  }
} else {
  if ((color.x <= 0.9)) {
    x = 0.0;
    y = 0.0;
    (*hd) = true;
  }
}
v.x = (${w} * x);
v.y = (${w} * y);
}`,
  },
  "cut_wood": {
    params: [{ name: "shiftX", def: 0 }, { name: "shiftY", def: 0 }, { name: "freq", def: 1.8 }, { name: "smooth", def: 1 }, { name: "LineCount", def: 20 }, { name: "LineWidth", def: 0.2 }, { name: "mode", def: 1 }, { name: "zoom", def: 2.5 }, { name: "invert", def: 0 }],
    verified: false, priority: 0, flags: ["hide"], types: ["2D","BASE_SHAPE","SIMULATION"],
    funcNames: ["Mat2","powc","cut_wood_random","cut_wood_noise","Mat2_Init","cut_wood_rotate","times","cut_wood_twist","cut_wood_line"],
    funcs: `struct Mat2 {
  a00: f32,
  a01: f32,
  a10: f32,
  a11: f32,
}

fn powc(x: f32, y: f32) -> f32 {
  if (x >= 0.0) { return pow(x, y); }
  let yi = round(y);
  if (abs(y - yi) > 1e-6) { return pow(x, y); }
  let m = pow(-x, y);
  return select(m, -m, (i32(yi) & 1) != 0);
}

fn cut_wood_random(st: vec2f) -> f32 {
  return fract((sin(dot(vec2f(st.x, st.y), vec2f(12.9898, 78.233))) * 43758.5453123));
}

fn cut_wood_noise(c: vec2f, density: f32) -> f32 {
  var cu: vec2f = fract((c * vec2f(density)));
  var ci: vec2f = floor((c * vec2f(density)));
  var bl: f32 = cut_wood_random(ci);
  var br: f32 = cut_wood_random((ci + vec2f(1.0, 0.0)));
  var tl: f32 = cut_wood_random((ci + vec2f(0.0, 1.0)));
  var tr: f32 = cut_wood_random((ci + vec2f(1.0, 1.0)));
  cu = smoothstep(vec2f(0.0), vec2f(1.0), cu);
  var b: f32 = mix(bl, br, cu.x);
  var t_: f32 = mix(tl, tr, cu.x);
  var v_: f32 = mix(b, t_, cu.y);
  return v_;
}

fn Mat2_Init(m: ptr<function, Mat2>, v00: f32, v10: f32, v01: f32, v11: f32) {
  (*m).a00 = v00;
  (*m).a01 = v01;
  (*m).a10 = v10;
  (*m).a11 = v11;
}

fn cut_wood_rotate(angle: f32) -> Mat2 {
  var c: f32 = cos(angle);
  var s: f32 = sin(angle);
  var mat: Mat2;
  Mat2_Init(&(mat), c, -s, s, c);
  return mat;
}

fn times(m: ptr<function, Mat2>, v_: vec2f) -> vec2f {
  return vec2f((((*m).a00 * v_.x) + ((*m).a01 * v_.y)), (((*m).a10 * v_.x) + ((*m).a11 * v_.y)));
}

fn cut_wood_twist(c: vec2f, angle: f32) -> vec2f {
  var m: Mat2;
  m = cut_wood_rotate(angle);
  var t0: vec2f = times(&(m), (c - vec2f(0.5)));
  return (t0 + vec2f(0.5));
}

fn cut_wood_line(c: vec2f, width: f32) -> f32 {
  var smoothing: f32 = 0.04;
  return (smoothstep((0.5 - width), ((0.5 - width) + smoothing), c.y) - smoothstep(((0.5 + width) - smoothing), (0.5 + width), c.y));
}`,
    code: (w, p) => `{
var x: f32;
var y: f32;
var px_center: f32;
var py_center: f32;
if ((min(max(${p[6]}, 0.0), 1.0) == 0)) {
  x = t.x;
  y = t.y;
  px_center = 0.0;
  py_center = 0.0;
} else {
  x = rnd(rs);
  y = rnd(rs);
  px_center = 0.5;
  py_center = 0.5;
}
var st: vec2f = vec2f((x * ${p[7]}), (y * ${p[7]}));
st = (st + vec2f(${p[0]}, ${p[1]}));
var sti: vec2f = floor(st);
st = cut_wood_twist(st, powc(cut_wood_noise(st, min(max(${p[2]}, 0.1), 2.0)), min(max(${p[3]}, 0.0), 1.0)));
var c: vec2f = fract((st * vec2f(1.0, min(max(${p[4]}, 1.0), 50.0))));
var background: f32 = 0.0;
var foreground: f32 = 1.0;
var color: f32 = mix(background, foreground, cut_wood_line(c, min(max(${p[5]}, 0.1), 0.5)));
(*hd) = false;
if ((min(max(${p[8]}, 0.0), 1.0) == 0)) {
  if ((color > 0.0)) {
    x = 0;
    y = 0;
    (*hd) = true;
  }
} else {
  if ((color <= 0.0)) {
    x = 0;
    y = 0;
    (*hd) = true;
  }
}
v.x = (${w} * (x - px_center));
v.y = (${w} * (y - py_center));
}`,
  },
  "pixel_flow": {
    params: [{ name: "angle", def: 90 }, { name: "len", def: 0.1 }, { name: "width", def: 200 }, { name: "seed", def: 42 }, { name: "enable_dc", def: 0 }],
    verified: false, priority: 0, flags: ["dc"], types: ["2D","DC"],
    funcNames: ["pixel_flow_hash"],
    funcs: `fn pixel_flow_hash(a_in: i32) -> f32 {
  var a: i32 = a_in;
  a = ((a ^ 61) ^ (a >> 16));
  a = (a + (a << 3));
  a = (a ^ (a >> 4));
  a = (a * 668265261);
  a = (a ^ (a >> 15));
  return (f32(a) / exp2(32.0));
}`,
    code: (w, p) => `{
var a_rad: f32 = (${p[0]} * 0.0174532925);
var sina: f32 = sin(a_rad);
var cosa: f32 = cos(a_rad);
var blockx: i32 = i32(floor((t.x * ${p[2]})));
blockx = i32((f32(blockx) + (2.0 - (4.0 * pixel_flow_hash(i32(((f32(blockx) * ${p[3]}) + 1)))))));
var blocky: i32 = i32(floor((t.y * ${p[2]})));
blocky = i32((f32(blocky) + (2.0 - (4.0 * pixel_flow_hash(i32(((f32(blocky) * ${p[3]}) + 1)))))));
var fLen: f32 = ((pixel_flow_hash(i32((f32(blocky) + (f32(blockx) * -(${p[3]}))))) + pixel_flow_hash(i32((f32(blockx) + ((f32(blocky) * ${p[3]}) / 2))))) * 0.5);
var r01: f32 = rnd(rs);
var fade: f32 = ((((1.0 * r01) * r01) * r01) * r01);
v.x += (((${w} * ${p[1]}) * cosa) * fade);
v.y += (((${w} * ${p[1]}) * sina) * fade);
if ((min(max(${p[4]}, 0.0), 1.0) == 1)) {
  (*cp) = r01;
}
}`,
  },
  "cut_mandala": {
    params: [{ name: "seed", def: 1000 }, { name: "mode", def: 1 }, { name: "time", def: 0 }, { name: "zoom", def: 2 }, { name: "invert", def: 1 }],
    verified: false, priority: 0, flags: ["hide"], types: ["2D","BASE_SHAPE","SIMULATION"],
    funcNames: ["mmod2","cut_mandala_spiral","cut_mandala_rose","rose2","cut_mandala_circle"],
    funcs: `fn mmod2(a: vec2f, b: vec2f) -> vec2f { return a - b * floor(a / b); }

fn cut_mandala_spiral(p_: vec2f, width: f32) -> f32 {
  var d: f32 = 0.0;
  d += smoothstep(1.0, 0.0, (width * abs((p_.x - ((0.5 * p_.y) / PI)))));
  d += smoothstep(1.0, 0.0, (width * abs((p_.x - ((0.5 * abs(p_.y)) / PI)))));
  d += smoothstep(1.0, 0.0, (width * abs((abs(p_.x) - ((0.5 * p_.y) / PI)))));
  d += smoothstep(1.0, 0.0, (width * abs((abs(p_.x) - ((0.5 * abs(p_.y)) / PI)))));
  return d;
}

fn cut_mandala_rose(p__in: vec2f, t_: f32, width: f32) -> f32 {
  var p_: vec2f = p__in;
  var a0: f32 = 6.0;
  var d: f32 = 0.0;
  p_.x *= (7.0 + (8.0 * t_));
  d += smoothstep(1.0, 0.0, (width * abs((p_.x - sin((a0 * p_.y))))));
  d += smoothstep(1.0, 0.0, (width * abs((p_.x - abs(sin((a0 * p_.y)))))));
  d += smoothstep(1.0, 0.0, (width * abs((abs(p_.x) - sin((a0 * p_.y))))));
  d += smoothstep(1.0, 0.0, (width * abs((abs(p_.x) - abs(sin((a0 * p_.y)))))));
  return d;
}

fn rose2(p__in: vec2f, t_: f32, width: f32) -> f32 {
  var p_: vec2f = p__in;
  var a0: f32 = 6.0;
  var d: f32 = 0.0;
  p_.x *= (7.0 + (8.0 * t_));
  d += smoothstep(1.0, 0.0, (width * abs((p_.x - cos((a0 * p_.y))))));
  d += smoothstep(1.0, 0.0, (width * abs((p_.x - abs(cos((a0 * p_.y)))))));
  d += smoothstep(1.0, 0.0, (width * abs((abs(p_.x) - cos((a0 * p_.y))))));
  d += smoothstep(1.0, 0.0, (width * abs((abs(p_.x) - abs(cos((a0 * p_.y)))))));
  return d;
}

fn cut_mandala_circle(p_: vec2f, r_: f32, width: f32) -> f32 {
  var d: f32 = 0.0;
  d += smoothstep(1.0, 0.0, (width * abs((p_.x - r_))));
  return d;
}`,
    code: (w, p) => `{
var x: f32;
var y: f32;
if ((min(max(${p[1]}, 0.0), 1.0) == 0)) {
  x = t.x;
  y = t.y;
} else {
  x = (rnd(rs) - 0.5);
  y = (rnd(rs) - 0.5);
}
var p_: vec2f = vec2f((x * ${p[3]}), (y * ${p[3]}));
var f: vec2f = vec2f(sqrt(((p_.x * p_.x) + (p_.y * p_.y))), atan2(p_.y, p_.x));
var T0: f32 = cos((0.3 * ${p[2]}));
var T1: f32 = (0.5 + (0.5 * cos((0.3 * ${p[2]}))));
var T2: f32 = 1.0;
var m0: f32 = 0.0;
var m1: f32 = 0.0;
var m2: f32 = 0.0;
var m3: f32 = 0.0;
var m4: f32 = 0.0;
if ((f.x < 0.7325)) {
  f.y += (0.1 * ${p[2]});
  var c: vec2f;
  var f2: vec2f;
  c = vec2f((0.225 - (0.1 * T0)), (PI / 4.0));
  if ((f.x < 0.25)) {
    for (var i: f32 = 0.0; (i < 2.0); i += 1.0) {
      f2 = (mmod2(f, c) - (c * vec2f(0.5)));
      m0 += cut_mandala_spiral(vec2f(f2.x, f2.y), 192.0);
    }
  }
  c = vec2f((0.225 + (0.1 * T0)), (PI / 4.0));
  if ((f.x > 0.43)) {
    for (var i: f32 = 0.0; (i < 2.0); i += 1.0) {
      f.y += (PI / 8.0);
      f2 = (mmod2(f, c) - (c * vec2f(0.5)));
      m1 += cut_mandala_rose((f2 * vec2f((0.75 - (0.5 * T0)))), (0.4 * T1), 24.0);
      m1 += rose2((f2 * vec2f((0.5 + (0.5 * T1)))), (0.2 + (0.2 * T0)), 36.0);
    }
  }
  c = vec2f((0.6 - (0.2 * T0)), (PI / 4.0));
  if ((f.x > 0.265)) {
    for (var i: f32 = 0.0; (i < 2.0); i += 1.0) {
      f.y += (PI / 8.0);
      f2 = (mmod2(f, c) - (c * vec2f(0.5)));
      m2 += cut_mandala_spiral(vec2f(((0.25 + (0.5 * T1)) * f2.x), f2.y), 392.0);
      m2 += rose2((f2 * vec2f((1.0 + (0.25 * T0)))), 0.5, 24.0);
    }
  }
  c = vec2f((0.4 + (0.23 * T0)), (PI / 4.0));
  if ((f.x < 0.265)) {
    for (var i: f32 = 0.0; (i < 2.0); i += 1.0) {
      f.y += (PI / 8.0);
      f2 = (mmod2(f, c) - (c * vec2f(0.5)));
      m3 += cut_mandala_spiral(vec2f(f2.x, f2.y), 256.0);
      m3 += cut_mandala_rose(f2, (1.5 * T1), 16.0);
    }
  }
  m4 += cut_mandala_circle(f, 0.04, 192.0);
  m4 += cut_mandala_circle(f, 0.265, 192.0);
  m4 += cut_mandala_circle(f, 0.43, 192.0);
}
m4 += cut_mandala_circle(f, 0.7325, 192.0);
var z: f32 = ((((m0 + m1) + m2) + m3) + m4);
z *= z;
z = clamp(z, 0.0, 1.0);
var color: f32 = z;
(*hd) = false;
if ((min(max(${p[4]}, 0.0), 1.0) == 0)) {
  if ((color > 0.0)) {
    x = 0;
    y = 0;
    (*hd) = true;
  }
} else {
  if ((color <= 0.0)) {
    x = 0;
    y = 0;
    (*hd) = true;
  }
}
v.x = (${w} * x);
v.y = (${w} * y);
}`,
  },
  "sym_ng13": {
    params: [{ name: "radius", def: 0 }, { name: "stepx", def: 0 }, { name: "stepy", def: 0 }],
    verified: false, priority: 0, flags: [], types: ["2D"],
    funcNames: ["Mathc","transfhcf"],
    funcs: `struct Mathc {
  a: f32,
  b: f32,
  c: f32,
  d: f32,
  e: f32,
  f: f32,
}

fn transfhcf(xy: vec2f, a: f32, b: f32, c: f32, d: f32, e: f32, f: f32) -> vec2f {
  var xt: f32 = (((a * xy.x) + (b * xy.y)) + c);
  var yt: f32 = (((d * xy.x) + (e * xy.y)) + f);
  return vec2f(xt, yt);
}`,
    code: (w, p) => `{
var x: f32;
var y: f32;
var spacex: f32 = sqrt(((${p[0]} * ${p[0]}) / 2.0));
var spacey: f32 = spacex;
var sx: f32 = (${p[1]} / 2.0);
var sy: f32 = (${p[2]} / 2.0);
var Tx: array<Mathc, 6> = array<Mathc, 6>(Mathc(1.0, 0.0, 0.0, 0.0, -1.0, 0.0), Mathc(-0.5, -0.866, -0.0, -0.866, 0.5, 0.0), Mathc(-0.5, 0.866, -0.0, 0.866, 0.5, 0.0), Mathc(1.0, 0.0, 0.0, 0.0, -1.0, 0.0), Mathc(-0.5, -0.866, -0.0, -0.866, 0.5, 0.0), Mathc(-0.5, 0.866, -0.0, 0.866, 0.5, 0.0));
Tx[0].c = -sx;
Tx[0].f = -sy;
Tx[1].c = -sx;
Tx[1].f = -sy;
Tx[2].c = -sx;
Tx[2].f = -sy;
Tx[3].c = -sx;
Tx[3].f = -sy;
Tx[4].c = sx;
Tx[4].f = sy;
Tx[5].c = sx;
Tx[5].f = sy;
Tx[6].c = sx;
Tx[6].f = sy;
Tx[7].c = sx;
Tx[7].f = sy;
x = t.x;
y = t.y;
var z: vec2f = vec2f(x, y);
z = (z + vec2f(spacex, spacey));
var index: i32 = i32((f32((24 / 4)) * rnd(rs)));
var f: vec2f = transfhcf(z, Tx[index].a, Tx[index].b, Tx[index].c, Tx[index].d, Tx[index].e, Tx[index].f);
v.x += (${w} * f.x);
v.y += (${w} * f.y);
}`,
  },
  "post_point_crop": {
    params: [{ name: "x_offset", def: 0 }, { name: "y_offset", def: 0 }, { name: "z_offset", def: 0 }, { name: "point_hide_enable", def: 1 }, { name: "point_crop_enable", def: 1 }, { name: "x_width", def: 0 }, { name: "y_width", def: 0 }, { name: "z_width", def: 0 }],
    verified: false, priority: 1, flags: ["dc","hide","stateful","z"], types: ["2D","CROP","POST"],
    funcNames: ["jw_jwf0_post_scrop_x","jw_jwf0_post_scrop_y","jw_jwf0_post_scrop_z","jw_jwf0_post_scrop_c"],
    funcs: `var<private> jw_jwf0_post_scrop_x: f32;

var<private> jw_jwf0_post_scrop_y: f32;

var<private> jw_jwf0_post_scrop_z: f32;

var<private> jw_jwf0_post_scrop_c: f32;`,
    code: (_w, p) => `{
var zero: i32 = select(0, 1, (((v.x == (0 + ${p[0]})) && (v.y == (0 + ${p[1]}))) && (pz_ == (0 + ${p[2]}))));
var boundaryX: i32 = select(0, 1, (((v.x - ${p[0]}) <= ${p[5]}) && ((v.x - ${p[0]}) >= -(${p[5]}))));
var boundaryY: i32 = select(0, 1, (((v.y - ${p[1]}) <= ${p[6]}) && ((v.y - ${p[1]}) >= -(${p[6]}))));
var boundaryZ: i32 = select(0, 1, ((((pz_ - ${p[2]}) <= ${p[7]}) && ((pz_ - ${p[2]}) >= -(${p[7]}))) && (pz_ != 0)));
var boundaries: i32;
if ((((${p[5]} + ${p[6]}) + ${p[7]}) != 0)) {
  boundaries = select(0, 1, (((boundaryX != 0) || (boundaryY != 0)) || (boundaryZ != 0)));
} else {
  boundaries = zero;
}
if ((boundaries != 0)) {
  if ((min(max(${p[4]}, 0.0), 1.0) == 1)) {
    v.x = jw_jwf0_post_scrop_x;
    v.y = jw_jwf0_post_scrop_y;
    pz_ = jw_jwf0_post_scrop_z;
    (*cp) = jw_jwf0_post_scrop_c;
  }
  if ((min(max(${p[3]}, 0.0), 1.0) == 1)) {
    (*hd) = true;
  }
} else {
  if ((min(max(${p[3]}, 0.0), 1.0) == 1)) {
    (*hd) = false;
  }
  if ((min(max(${p[4]}, 0.0), 1.0) == 1)) {
    jw_jwf0_post_scrop_x = v.x;
    jw_jwf0_post_scrop_y = v.y;
    jw_jwf0_post_scrop_z = pz_;
    jw_jwf0_post_scrop_c = (*cp);
  }
}
}`,
  },
  "voronoi_fold": {
    params: [{ name: "scale", def: 1 }, { name: "fold", def: 0.5 }],
    verified: false, priority: 0, flags: [], types: ["2D"],
    code: (w, p) => `{
var vf_scale: f32 = max(abs(${p[0]}), 0.01);
var vf_cx: f32 = floor((t.x / vf_scale));
var vf_cy: f32 = floor((t.y / vf_scale));
var nearest_x: f32 = 0.0;
var nearest_y: f32 = 0.0;
var vf_min_d: f32 = 10000000000.0;
for (var di: i32 = -1; (di <= 1); di++) {
  for (var dj: i32 = -1; (dj <= 1); dj++) {
    var cell_x: f32 = (vf_cx + f32(di));
    var cell_y: f32 = (vf_cy + f32(dj));
    var vf_hx: f32 = (sin(((cell_x * 127.1) + (cell_y * 311.7))) * 43758.5453);
    vf_hx = (vf_hx - floor(vf_hx));
    var vf_hy: f32 = (sin(((cell_x * 269.5) + (cell_y * 183.3))) * 43758.5453);
    vf_hy = (vf_hy - floor(vf_hy));
    var site_x: f32 = ((cell_x + vf_hx) * vf_scale);
    var site_y: f32 = ((cell_y + vf_hy) * vf_scale);
    var dx: f32 = (t.x - site_x);
    var dy: f32 = (t.y - site_y);
    var vf_d: f32 = sqrt(((dx * dx) + (dy * dy)));
    if ((vf_d < vf_min_d)) {
      vf_min_d = vf_d;
      nearest_x = site_x;
      nearest_y = site_y;
    }
  }
}
v.x += (${w} * (nearest_x + ((t.x - nearest_x) * (1.0 - ${p[1]}))));
v.y += (${w} * (nearest_y + ((t.y - nearest_y) * (1.0 - ${p[1]}))));
}`,
  },
  "worley": {
    params: [{ name: "scale", def: 1 }, { name: "jitter", def: 0.8 }],
    verified: false, priority: 0, flags: [], types: ["2D"],
    code: (w, p) => `{
var wo_s: f32 = max(abs(${p[0]}), 0.01);
var wo_j: f32 = clamp(${p[1]}, 0.0, 1.0);
var wo_cx: f32 = floor((t.x / wo_s));
var wo_cy: f32 = floor((t.y / wo_s));
var wo_min_d: f32 = 10000000000.0;
var wo_nx: f32 = 0.0;
var wo_ny: f32 = 0.0;
for (var di: i32 = -1; (di <= 1); di++) {
  for (var dj: i32 = -1; (dj <= 1); dj++) {
    var cell_x: f32 = (wo_cx + f32(di));
    var cell_y: f32 = (wo_cy + f32(dj));
    var wo_hx: f32 = (sin(((cell_x * 127.1) + (cell_y * 311.7))) * 43758.5453);
    wo_hx = (wo_hx - floor(wo_hx));
    var wo_hy: f32 = (sin(((cell_x * 269.5) + (cell_y * 183.3))) * 43758.5453);
    wo_hy = (wo_hy - floor(wo_hy));
    var site_x: f32 = (((cell_x + (wo_hx * wo_j)) + ((1.0 - wo_j) * 0.5)) * wo_s);
    var site_y: f32 = (((cell_y + (wo_hy * wo_j)) + ((1.0 - wo_j) * 0.5)) * wo_s);
    var dx: f32 = (t.x - site_x);
    var dy: f32 = (t.y - site_y);
    var wo_d: f32 = sqrt(((dx * dx) + (dy * dy)));
    if ((wo_d < wo_min_d)) {
      wo_min_d = wo_d;
      wo_nx = site_x;
      wo_ny = site_y;
    }
  }
}
v.x += (${w} * ((t.x - wo_nx) / (wo_s + 0.000001)));
v.y += (${w} * ((t.y - wo_ny) / (wo_s + 0.000001)));
}`,
  },
};
