// AUTO-GENERATED by scripts/jwf-port/gen.ts — do not edit by hand.
// JWildfire ports that did NOT pass the oracle harness (see scripts/jwf-port/verified.json);
// kept out of the app registry, loaded only by the dev harness (src/dev/varTest.ts).

import type { JwfVariationDef } from './variations.jwf';

export const JWF_VARIATIONS_UNVERIFIED: Record<string, JwfVariationDef> = {
  "dc_gnarly": {
    params: [{ name: "mode", def: 1 }, { name: "scalex", def: 0.05 }, { name: "scaley", def: 0.05 }, { name: "freqx1", def: 3.5 }, { name: "freqy1", def: 3.5 }, { name: "freqx2", def: 2 }, { name: "freqy2", def: 2 }, { name: "freqx3", def: 5 }, { name: "freqy3", def: 5 }, { name: "dc", def: 1 }, { name: "color1", def: 5 }, { name: "color2", def: 5 }, { name: "fmag", def: 1 }, { name: "distort", def: 0 }, { name: "blur", def: 5 }, { name: "scale_z", def: 0 }, { name: "offset_z", def: 0 }, { name: "reset_z", def: 0 }],
    verified: false, priority: 0, flags: ["dc","z"], types: ["2D","DC"],
    funcNames: ["roundc","atan2j","sqrf"],
    funcs: `fn roundc(x: f32) -> f32 { return sign(x) * floor(abs(x) + 0.5); }

fn atan2j(y: f32, x: f32) -> f32 { if (x == 0.0 && y == 0.0) { return select(0.0, PI, (bitcast<u32>(x) >> 31u) == 1u) * select(1.0, -1.0, (bitcast<u32>(y) >> 31u) == 1u); } return atan2(y, x); }

fn sqrf(x: f32) -> f32 {
  return (x * x);
}`,
    code: (w, p) => `{
var x0: f32 = t.x;
var y0: f32 = t.y;
if ((${p[14]} > 0)) {
  var r_: f32 = ((rnd(rs) * 2) * PI);
  var sina: f32 = sin(r_);
  var cosa: f32 = cos(r_);
  r_ = (${p[14]} * ((((((rnd(rs) + rnd(rs)) + rnd(rs)) + rnd(rs)) + rnd(rs)) + rnd(rs)) - 3.0));
  x0 += (r_ * cosa);
  y0 += (r_ * sina);
} else if ((${p[14]} < 0)) {
  x0 += (((rnd(rs) * ${p[14]}) * 2.0) - ${p[14]});
  y0 += (((rnd(rs) * ${p[14]}) * 2.0) - ${p[14]});
}
var x1: f32;
var y1: f32;
switch i32(roundc(min(max(${p[0]}, 0.0), 8.0))) {
  case 1: {
    x1 = (cos(((${p[3]} * y0) + sin((${p[5]} * (y0 + sin((${p[7]} * y0))))))) * ${p[1]});
    y1 = (cos(((${p[4]} * x0) + sin((${p[6]} * (x0 + sin((${p[8]} * x0))))))) * ${p[2]});
  }
  case 2: {
    x1 = (sin(((${p[3]} * y0) + sin((${p[5]} * (y0 + cos((${p[7]} * y0))))))) * ${p[1]});
    y1 = (sin(((${p[4]} * x0) + sin((${p[6]} * (x0 + cos((${p[8]} * x0))))))) * ${p[2]});
  }
  case 3: {
    x1 = (cos(((${p[3]} * y0) + sin((${p[5]} * (x0 + sin((${p[7]} * y0))))))) * ${p[1]});
    y1 = (cos(((${p[4]} * x0) + sin((${p[6]} * (y0 + sin((${p[8]} * x0))))))) * ${p[2]});
  }
  case 4: {
    x1 = (sin(((${p[3]} * y0) + sin(sqrt(abs((${p[5]} * (y0 + cos((${p[7]} * y0))))))))) * ${p[1]});
    y1 = (sin(((${p[4]} * x0) + sin(sqrt(abs((${p[6]} * (x0 + cos((${p[8]} * x0))))))))) * ${p[2]});
  }
  case 5: {
    x1 = (cos(((${p[3]} * y0) + asinh((${p[5]} * (y0 + sin((${p[7]} * y0))))))) * ${p[1]});
    y1 = (cos(((${p[4]} * x0) + asinh((${p[6]} * (x0 + sin((${p[8]} * x0))))))) * ${p[2]});
  }
  case 6: {
    x1 = (cos(((${p[3]} * y0) + tan((${p[5]} * (y0 + sin((${p[7]} * y0))))))) * ${p[1]});
    y1 = (cos(((${p[4]} * x0) + tan((${p[6]} * (x0 + sin((${p[8]} * x0))))))) * ${p[2]});
  }
  case 7: {
    x1 = (sin(((${p[3]} * y0) + sin(sqrf((${p[5]} * (y0 + cos((${p[7]} * y0)))))))) * ${p[1]});
    y1 = (sin(((${p[4]} * x0) + sin(sqrf((${p[6]} * (x0 + cos((${p[8]} * x0)))))))) * ${p[2]});
  }
  case 8: {
    x1 = (sin(((${p[3]} * y0) + sin(sqrf((${p[5]} * (x0 + cos((${p[7]} * y0)))))))) * ${p[1]});
    y1 = (sin(((${p[4]} * x0) + sin(sqrf((${p[6]} * (y0 + cos((${p[8]} * x0)))))))) * ${p[2]});
  }
  case default: {
    x1 = (sin((${p[3]} * y0)) * ${p[1]});
    y1 = (sin((${p[4]} * x0)) * ${p[2]});
  }
}
var s1: f32 = (log(sqrt(((x1 * x1) + (y1 * y1)))) * ${p[13]});
v.x += ((${w} * (x0 + x1)) / 2);
v.y += ((${w} * (y0 + y1)) / 2);
if ((i32(roundc(min(max(${p[9]}, 0.0), 1.0))) != 0)) {
  (*cp) = (abs((cos(((x0 + (x1 * ${p[10]})) + s1)) + sin(((y0 + (y1 * ${p[11]})) + s1)))) % min(max(${p[12]}, 0.05), 1.0));
}
var dz: f32 = (((*cp) * ${p[15]}) + ${p[16]});
if ((i32(roundc(min(max(${p[17]}, 0.0), 1.0))) > 0)) {
  pz_ = dz;
} else {
  pz_ += dz;
}
}`,
  },
  "dc_circuits": {
    params: [{ name: "Seed", def: 1000000 }, { name: "time", def: 0 }, { name: "rate", def: 0.8 }, { name: "intensity", def: 0.9 }, { name: "focus", def: 1.5 }, { name: "pulse", def: 10 }, { name: "glow", def: 2 }, { name: "loops", def: 15 }, { name: "zoom", def: 1 }, { name: "ColorOnly", def: 0 }, { name: "Gradient", def: 0 }, { name: "scale_z", def: 0 }, { name: "offset_z", def: 0 }, { name: "reset_z", def: 1 }],
    verified: false, priority: 0, flags: ["dc","rgb","z"], types: ["SIMULATION","DC","BASE_SHAPE"],
    funcNames: ["Mat2","read_imageStepMode","atan2j","powc","Mat2_Init","times","dc_circuits_formula","dc_circuits_getRGBColor","dbl2int","greyscale","distance_color"],
    funcs: `struct Mat2 {
  a00: f32,
  a01: f32,
  a10: f32,
  a11: f32,
}

fn read_imageStepMode(base: u32, n: i32, t: f32) -> vec4f { return pal[base + u32(clamp(t, 0.0, 0.99999) * f32(max(n, 1)))]; }

fn atan2j(y: f32, x: f32) -> f32 { if (x == 0.0 && y == 0.0) { return select(0.0, PI, (bitcast<u32>(x) >> 31u) == 1u) * select(1.0, -1.0, (bitcast<u32>(y) >> 31u) == 1u); } return atan2(y, x); }

fn powc(x: f32, y: f32) -> f32 {
  if (x >= 0.0) { return pow(x, y); }
  let yi = round(y);
  if (abs(y - yi) > 1e-6) { return pow(x, y); }
  let m = pow(-x, y);
  return select(m, -m, (i32(yi) & 1) != 0);
}

fn Mat2_Init(m: ptr<function, Mat2>, v00: f32, v10: f32, v01: f32, v11: f32) {
  (*m).a00 = v00;
  (*m).a01 = v01;
  (*m).a10 = v10;
  (*m).a11 = v11;
}

fn times(m: ptr<function, Mat2>, v_: vec2f) -> vec2f {
  return vec2f((((*m).a00 * v_.x) + ((*m).a01 * v_.y)), (((*m).a10 * v_.x) + ((*m).a11 * v_.y)));
}

fn dc_circuits_formula(z_in: vec2f, t_: f32, loops: f32, zoom: f32, intensity: f32, glow: f32, pulse: f32) -> vec3f {
  var z: vec2f = z_in;
  var M: f32 = 0.0;
  var S: f32 = ((101.0 + glow) * intensity);
  var o: f32;
  var ot2: f32 = 1000.0;
  var ot: f32 = 1000.0;
  var K: f32 = floor(((loops / 4.0) + floor((5.0 * zoom))));
  var color: vec3f = vec3f(0.0, 0.0, 0.0);
  for (var i: i32 = 0; (i < 11); i++) {
    z = ((abs(z) / vec2f(clamp(dot(z, z), 0.1, 0.5))) - vec2f(t_));
    var l: f32 = length(z);
    o = min(max(abs(min(z.x, z.y)), (-l + 0.25)), abs((l - 0.25)));
    ot = min(ot, o);
    ot2 = min((l * 0.1), ot2);
    M = max(M, (f32(i) * (1.0 - abs(sign((ot - o))))));
    if ((K <= 0.0)) {
      break;
    }
    K -= 1.0;
  }
  M += 1.0;
  var w_: f32 = ((intensity * zoom) * M);
  var circ: f32 = powc((max(0.0, (w_ - ot2)) / w_), 6.0);
  var t99: f32 = powc((max(0.0, (w_ - ot)) / w_), 0.25);
  S = (S + max(t99, circ));
  var t1: vec3f = (vec3f(0.1, 0.1, 0.1) + vec3f(0.45, 0.75, (M * 0.1)));
  var col: vec3f = normalize(t1);
  var t100: f32 = (0.4 + mmod((((M / 9.0) - (t_ * pulse)) + (ot2 * 2.0)), 1.0));
  var t2: vec3f = vec3f(t100, t100, t100);
  color = (color + (col * t2));
  var f1: f32 = ((circ * (10.0 - M)) * 3.0);
  color = (color + (vec3f(1.0, 0.7, 0.3) * vec3f(f1)));
  return color;
}

fn dc_circuits_getRGBColor(pos: vec2f, time: f32, rate: f32, zoom: f32, focus: f32, loops: f32, glow: f32, intensity: f32, pulse: f32) -> vec3f {
  var color: vec3f = vec3f(0.0, 0.0, 0.0);
  var S: f32 = ((101.0 + glow) * intensity);
  var center: vec2f = vec2f(0.0, 0.0);
  var R: f32 = 0.0;
  var N: f32 = ((time * 0.01) * rate);
  var T: f32 = (2.0 * rate);
  if ((N > (6.0 * rate))) {
    R += 1.0;
    N -= ((R * 8.0) * rate);
  }
  if ((N < (4.0 * rate))) {
    T += N;
  } else {
    T = ((8.0 * rate) - N);
  }
  var Z: f32 = (1.05 - zoom);
  var uv: vec2f = (pos + center);
  var sph: f32 = (length(uv) * 0.1);
  sph = (sqrt((1.0 - (sph * sph))) * 2.0);
  var a: f32 = (T * PI);
  var b: f32 = (a + T);
  var c: f32 = (cos(a) + sin(b));
  var M: Mat2;
  Mat2_Init(&(M), cos(b), sin(b), -(sin(b)), cos(b));
  uv = times(&(M), uv);
  var M1: Mat2;
  Mat2_Init(&(M1), cos(a), -(sin(a)), sin(a), cos(a));
  uv = times(&(M1), uv);
  uv = (uv - (vec2f(sin(c), cos(c)) / vec2f(PI)));
  uv = (uv * vec2f(Z));
  var pix: f32 = (((0.5 / 1000.0) * Z) / sph);
  var dof: f32 = ((zoom * focus) + (T * 0.25));
  var L: f32 = floor(loops);
  for (var aa: i32 = 0; (aa < 24); aa++) {
    var aauv: vec2f = floor(vec2f((f32(aa) / 6.0), mmod(f32(aa), 6.0)));
    color = dc_circuits_formula((uv + ((aauv * vec2f(pix)) * vec2f(dof))), T, loops, zoom, intensity, glow, pulse);
    if ((L <= 0.0)) {
      break;
    }
    L = (L - 1.0);
  }
  S = (S / floor(loops));
  color = (color / vec3f(floor(loops)));
  var colo: vec3f = (mix(vec3f(0.15, 0.15, 0.15), color, S) * vec3f((1.0 - length(pos))));
  colo = (colo * vec3f(1.2, 1.1, 1.0));
  return colo;
}

fn dbl2int(theColor: vec3f) -> vec3i {
  var red: i32 = max(0, min(255, i32(floor((theColor.x * 256.0)))));
  var green: i32 = max(0, min(255, i32(floor((theColor.y * 256.0)))));
  var blue: i32 = max(0, min(255, i32(floor((theColor.z * 256.0)))));
  return vec3i(red, green, blue);
}

fn greyscale(r_: i32, g: i32, b: i32) -> f32 {
  var lum: i32;
  var red: i32;
  var green: i32;
  var blue: i32;
  red = i32((f32(r_) * 0.299));
  green = i32((f32(g) * 0.587));
  blue = i32((f32(b) * 0.114));
  lum = ((red + green) + blue);
  return (f32(lum) / 255.0);
}

fn distance_color(p_red: f32, p_green: f32, p_blue: f32, red: f32, green: f32, blue: f32) -> f32 {
  var dist_r: f32 = abs((p_red - red));
  var dist_g: f32 = abs((p_green - green));
  var dist_b: f32 = abs((p_blue - blue));
  var dist_3d_sqd: f32 = (((dist_r * dist_r) + (dist_g * dist_g)) + (dist_b * dist_b));
  return dist_3d_sqd;
}`,
    code: (w, p) => `{
var colorA_: f32 = 1.0;
var x: f32;
var y: f32;
var color: vec3f = vec3f(1.0, 1.0, 0.0);
var z: f32 = 0.5;
if ((${p[9]} == 1)) {
  x = t.x;
  y = t.y;
} else {
  x = ((2.0 * rnd(rs)) - 1.0);
  y = ((2.0 * rnd(rs)) - 1.0);
}
var uv: vec2f = vec2f(x, y);
color = dc_circuits_getRGBColor(uv, ${p[1]}, ${p[2]}, ${p[8]}, ${p[4]}, ${p[7]}, ${p[6]}, ${p[3]}, ${p[5]});
{
  var zc_: vec3i = dbl2int(color);
  z = greyscale(i32(f32(zc_.x)), i32(f32(zc_.y)), i32(f32(zc_.z)));
}
if ((${p[10]} == 0)) {
  (*rgb).w = select(0.0, 1.0, true);
  (*rgb).x = color.x;
  (*rgb).y = color.y;
  (*rgb).z = color.z;
  colorA_ = 1.0;
} else if ((${p[10]} == 1)) {
  var pal_color: vec4f = vec4f(color.x, color.y, color.z, 1.0);
  var simcol: vec4f = pal_color;
  var diff: f32 = 1000000000.0;
  for (var index: i32 = 0; (index < 256); index++) {
    pal_color = read_imageStepMode(PALB_, 256, (f32(index) / f32(256)));
    var pal_color3: vec3f = vec3f(pal_color.x, pal_color.y, pal_color.z);
    var dvalue: f32 = distance_color(color.x, color.y, color.z, pal_color.x, pal_color.y, pal_color.z);
    if ((diff > dvalue)) {
      diff = dvalue;
      simcol = pal_color;
    }
  }
  (*rgb).w = select(0.0, 1.0, true);
  (*rgb).x = simcol.x;
  (*rgb).y = simcol.y;
  (*rgb).z = simcol.z;
  colorA_ = 1.0;
} else if ((${p[10]} == 2)) {
  var icolor: vec3i = dbl2int(color);
  var z: f32 = greyscale(i32(f32(icolor.x)), i32(f32(icolor.y)), i32(f32(icolor.z)));
  (*cp) = z;
}
v.x += (${w} * x);
v.y += (${w} * y);
var dz: f32 = ((z * ${p[11]}) + ${p[12]});
if ((${p[13]} == 1)) {
  pz_ = dz;
} else {
  pz_ += dz;
}
}`,
  },
};
