// Variation registry. Each entry emits a WGSL snippet that accumulates into `v`.
// Available in scope: t (vec2f, post-affine point, mutable), r2, r,
// th = atan2(x,y), ph = atan2(y,x), rs (ptr to rng state, use rnd(rs)),
// cp (ptr<function, f32> to the walker's palette coordinate — direct-color
// variations write *cp), hd (ptr<function, bool>, set to hide the point),
// mmod(a,b), PI. `w` is the weight expression, `p[i]` are parameter
// expressions, `A(i)` gives this xform's affine coefficients (0..5 = a..f).
//
// Two sources feed the registry: the hand-written set below (flam3 classics)
// and the JWildfire ports in variations.jwf.ts (generated by scripts/jwf-port,
// verified numerically against JWildfire's Java implementation). Verified
// ports take precedence so behaviour matches JWildfire; hand-written entries
// remain as fallbacks for anything the port pipeline does not cover.

import type { JwfVariationDef } from './variations.jwf.ts';

export interface VariationDef {
  params?: { name: string; def: number; int?: boolean }[];
  code: (w: string, p: string[], A: (i: number) => string) => string;
  /** JWildfire "prepost" pair: runs first in the stage (priority -2) on the input point (the inverse), while `code` runs last (priority 2) on the output. */
  preCode?: (w: string, p: string[], A: (i: number) => string) => string;
  /** JWildfire priority: -1 pre (mutates the input point t), 0 normal (adds to v), 1 post (mutates v). Default 0. */
  priority?: number;
  /** Module-scope WGSL (helper functions/consts) the snippet needs; codegen dedupes by name. */
  funcs?: string;
  funcNames?: string[];
  /** Descriptive flags (z, hide, dc, state, 3d, affine). */
  flags?: string[];
  /** JWildfire type tags (2D, 3D, BLUR, DC, PRE, POST, CROP, BASE_SHAPE, SIMULATION, …). */
  types?: string[];
  /** Hidden numeric slots after the params (filled by codegen's data hook, e.g. mesh buffer offsets); the snippet sees them as p[params.length + i]. */
  extra?: number;
  /** String resources (JWildfire "ressources") an instance may carry in `VarInstance.res` — file names or embedded
   *  text, imported from `<var>_<name>` hex attributes and exported the same way (`*_filename` names keep the basename).
   *  Used: `obj_filename` (obj_mesh_wf), `flame` (subflame_wf). */
  res?: string[];
  /** Default value of a resource when the instance carries none (exported in its place). */
  resDef?: Record<string, string>;
}

/** JWildfire's built-in default sub-flame (SubFlameWFFunc.DFLT_FLAME_XML) — what subflame_wf renders until another flame is set. */
export const DFLT_SUBFLAME_XML = '<flame name="JWildfire" version="0.35 (15.01.2012)" size="581 327" center="0.0 0.0" scale="63.5625" rotate="0.0" oversample="1" color_oversample="1" filter="1.0" quality="50.0" background="0.0 0.0 0.0" brightness="4.0" gamma="4.0" gamma_threshold="0.04" estimator_radius="9" estimator_minimum="0" estimator_curve="0.4" temporal_samples="1.0" cam_zoom="1.0" cam_pitch="0.0" cam_yaw="0.0" cam_persp="0.0" cam_zpos="0.0" cam_dof="0.0" shading_shading="FLAT" >\r\n' +
  '  <xform weight="37.974195875650885" color="0.0" symmetry="0.6363142683575415" waves2_wf="1.0" waves2_wf_scalex="0.05411632642405888" waves2_wf_scaley="0.07140430473672771" waves2_wf_freqx="5.665411884739101" waves2_wf_freqy="3.5622214535317194" waves2_wf_use_cos_x="0" waves2_wf_use_cos_y="0" waves2_wf_dampx="0.0" waves2_wf_dampy="-0.0749313500620006" popcorn2="1.1747945422649702E-4" popcorn2_x="1.0" popcorn2_y="0.5" popcorn2_c="1.5" coefs="0.29869999951569876 0.9193040710637221 -0.9193040710637221 0.29869999951569876 -1.6842788839099072 2.0224216083110305" chaos="1.0 1.0 1.0" />\r\n' +
  '  <xform weight="0.5" color="0.0" symmetry="-1.0" spherical3D="0.43660175471191676" coefs="1.0 0.0 0.0 1.0 0.0 0.0" chaos="1.0 1.0 1.0" />\r\n' +
  '  <xform weight="0.5" color="0.0" symmetry="-1.0" linear3D="1.0" coefs="0.9321767990927353 -0.36200333594211836 0.36200333594211836 0.9321767990927353 -0.1636856703682093 0.5528632251910492" chaos="1.0 1.0 1.0" />\r\n' +
  '  <palette count="256" format="RGB" >\r\n' +
  'D45334CF5635CA5936C55C38C05F39BC623AB7653BB2683DAD6B3EA86E3FA371409E7442\r\n' +
  '997743947A448F7D458B80478683488186497C894A778C4C728F4D6D924E68944F639751\r\n' +
  '5E9A525A9D5355A05450A3564BA65746A95841AC593CAF5B37B25C32B55D2DB85E29BB5F\r\n' +
  '24BE611FC1621AC46315C76410CA660BCD6706D06804D26A07D16C0AD06E0DCF710FCE73\r\n' +
  '12CD7615CC7818CB7A1BCA7D1EC97F21C88124C78427C68629C5882CC48B2FC38D32C28F\r\n' +
  '35C19238C0943BBF963EBE9941BE9B43BD9D46BCA049BBA24CBAA44FB9A752B8A955B7AB\r\n' +
  '58B6AE5AB5B05DB4B260B3B563B2B766B1B969B0BC6CAFBE6FAEC172ADC374ACC577ABC8\r\n' +
  '7AAACA7DA9CC80A9CD82A9CD85A8CD87A8CD8AA8CD8DA7CD8FA7CD92A7CD94A7CD97A6CD\r\n' +
  '9AA6CD9CA6CD9FA5CDA1A5CDA4A5CDA6A5CDA9A4CDACA4CDAEA4CDB1A3CDB3A3CDB6A3CC\r\n' +
  'B8A3CCBBA2CCBEA2CCC0A2CCC3A2CCC5A1CCC8A1CCCAA1CCCDA0CCD0A0CCD2A0CCD5A0CC\r\n' +
  'D79FCCDA9FCCDD9FCCDF9ECCE29ECCE49ECCE79ECCE99DCCEC9DCCEA9BC8E798C4E596C0\r\n' +
  'E394BCE091B7DE8FB3DB8DAFD98AABD788A7D486A3D2839FD0819BCD7F97CB7C93C87A8E\r\n' +
  'C6788AC47586C17382BF707EBD6E7ABA6C76B86972B6676EB3656AB16265AE6061AC5E5D\r\n' +
  'AA5B59A75955A55751A3544DA052499E50459C4D41994B3C97493894463492443090422C\r\n' +
  '8D3F288B3D24893B2087391E89381F8A37218B36238D35258E34268F332891322A92312B\r\n' +
  '93302D952F2F962E31972D32992D349A2C369B2B389C2A399E293B9F283DA0273FA22640\r\n' +
  'A32542A42444A62345A72247A82149AA204BAB1F4CAC1E4EAE1E50AF1D52B01C53B11B55\r\n' +
  'B31A57B41959B5185AB7175CB8165EB9155FBB1461BC1363BD1265BF1166BE1166BC1066\r\n' +
  'BA1065B71064B50F63B30F63B10F62AF0E61AD0E60AB0E60A90E5FA70D5EA50D5DA30D5C\r\n' +
  'A10C5C9F0C5B9D0C5A9B0B59990B59960B58940A57920A56900A558E09558C09548A0953\r\n' +
  '88085286085284085182075080074F7E074F7C064E7A064D78064C75054B73054B71054A\r\n' +
  '6F04496D04486B0448690347</palette>\r\n' +
  '</flame>\r\n';

/** obj_mesh_primitive_wf / obj_mesh_wf shared parameter list (after the primitive index), GPU sampler and snippet. */
const MESH_PARAMS = [
  { name: 'scale_x', def: 1 }, { name: 'scale_y', def: 1 }, { name: 'scale_z', def: 1 },
  { name: 'offset_x', def: 0 }, { name: 'offset_y', def: 0 }, { name: 'offset_z', def: 0 },
  { name: 'subdiv_level', def: 0, int: true }, { name: 'subdiv_smooth_passes', def: 12, int: true }, { name: 'subdiv_smooth_lambda', def: 0.42 }, { name: 'subdiv_smooth_mu', def: -0.45 },
  { name: 'blend_colormap', def: 0, int: true }, { name: 'displ_amount', def: 0.1 }, { name: 'blend_displ_map', def: 0, int: true }, { name: 'receive_only_shadows', def: 0, int: true },
];
const MESH_FUNCS = `fn meshPick(cdfBase: u32, n: u32, u: f32) -> u32 {
  // binary search of the face CDF (JWildfire: pContext.random(faceCount) over the area-replicated face list)
  var lo = 0u; var hi = n - 1u;
  while (lo < hi) { let mid = (lo + hi) >> 1u; if (mesh[cdfBase + mid] < u) { lo = mid + 1u; } else { hi = mid; } }
  return lo;
}`;
/** `b` = index of scale_x in p (0 for obj_mesh_wf, 1 after `primitive`); the 3 hidden slots follow the 14 params. */
const meshCode = (w: string, p: string[], b: number) => `{ let mc = u32(${p[b + 15]});
  if (mc > 0u) {
    let fi = meshPick(u32(${p[b + 14]}), mc, rnd(rs));
    let tb = u32(${p[b + 16]}) + fi * 9u;
    let p1 = vec3f(mesh[tb], mesh[tb + 1u], mesh[tb + 2u]) * vec3f(${p[b]}, ${p[b + 1]}, ${p[b + 2]}) + vec3f(${p[b + 3]}, ${p[b + 4]}, ${p[b + 5]});
    let p2 = vec3f(mesh[tb + 3u], mesh[tb + 4u], mesh[tb + 5u]) * vec3f(${p[b]}, ${p[b + 1]}, ${p[b + 2]}) + vec3f(${p[b + 3]}, ${p[b + 4]}, ${p[b + 5]});
    let p3 = vec3f(mesh[tb + 6u], mesh[tb + 7u], mesh[tb + 8u]) * vec3f(${p[b]}, ${p[b + 1]}, ${p[b + 2]}) + vec3f(${p[b + 3]}, ${p[b + 4]}, ${p[b + 5]});
    let sr1 = sqrt(rnd(rs)); let r2_ = rnd(rs);
    let b = sr1 * (1.0 - r2_); let c = r2_ * sr1; // a = 1 − sr1
    // p1 + b·(p2−p1) + c·(p3−p1): a coordinate shared by the three vertices stays EXACTLY that value (JWildfire's
    // double a·p1+b·p2+c·p3 rounds back to the same float; in f32 the plain sum would jitter by an ulp and the
    // z-buffer normals of an axis-aligned face would no longer be exact — which the AO relies on)
    let q = p1 + b * (p2 - p1) + c * (p3 - p1);
    v += ${w} * q.xy;
    pz_ += ${w} * q.z;
  } }`;

const HAND_VARIATIONS: Record<string, VariationDef> = {
  linear: { code: (w) => `v += ${w} * t;` },

  sinusoidal: { code: (w) => `v += ${w} * sin(t);` },

  spherical: { code: (w) => `v += (${w} / r2) * t;` },

  swirl: {
    code: (w) => `{ let sw_s = sin(r2); let sw_c = cos(r2);
  v += ${w} * vec2f(t.x*sw_s - t.y*sw_c, t.x*sw_c + t.y*sw_s); }`,
  },

  horseshoe: {
    code: (w) => `v += (${w} / r) * vec2f((t.x - t.y)*(t.x + t.y), 2.0*t.x*t.y);`,
  },

  polar: { code: (w) => `v += ${w} * vec2f(th / PI, r - 1.0);` },

  handkerchief: { code: (w) => `v += ${w} * r * vec2f(sin(th + r), cos(th - r));` },

  heart: { code: (w) => `v += ${w} * r * vec2f(sin(th * r), -cos(th * r));` },

  disc: {
    code: (w) => `v += ${w} * (th / PI) * vec2f(sin(PI * r), cos(PI * r));`,
  },

  spiral: {
    code: (w) => `v += (${w} / r) * vec2f(cos(th) + sin(r), sin(th) - cos(r));`,
  },

  hyperbolic: { code: (w) => `v += ${w} * vec2f(sin(th) / r, r * cos(th));` },

  diamond: { code: (w) => `v += ${w} * vec2f(sin(th) * cos(r), cos(th) * sin(r));` },

  ex: {
    code: (w) => `{ let ex_a = sin(th + r); let ex_b = cos(th - r);
  let ex_a3 = ex_a*ex_a*ex_a; let ex_b3 = ex_b*ex_b*ex_b;
  v += ${w} * r * vec2f(ex_a3 + ex_b3, ex_a3 - ex_b3); }`,
  },

  julia: {
    code: (w) => `{ let jl_o = select(0.0, PI, rnd(rs) < 0.5);
  v += ${w} * sqrt(r) * vec2f(cos(0.5*th + jl_o), sin(0.5*th + jl_o)); }`,
  },

  bent: {
    code: (w) => `v += ${w} * vec2f(select(t.x, 2.0*t.x, t.x < 0.0), select(t.y, 0.5*t.y, t.y < 0.0));`,
  },

  waves: {
    code: (w, _p, A) => `v += ${w} * vec2f(
  t.x + ${A(1)} * sin(t.y / (${A(2)}*${A(2)} + 1e-6)),
  t.y + ${A(4)} * sin(t.x / (${A(5)}*${A(5)} + 1e-6)));`,
  },

  fisheye: { code: (w) => `v += (${w} * 2.0 / (r + 1.0)) * vec2f(t.y, t.x);` },

  popcorn: {
    code: (w, _p, A) => `v += ${w} * vec2f(
  t.x + ${A(2)} * sin(tan(3.0*t.y)),
  t.y + ${A(5)} * sin(tan(3.0*t.x)));`,
  },

  exponential: {
    code: (w) => `{ let xp_e = exp(t.x - 1.0);
  v += ${w} * xp_e * vec2f(cos(PI * t.y), sin(PI * t.y)); }`,
  },

  power: {
    code: (w) => `v += ${w} * pow(r, sin(th)) * vec2f(cos(th), sin(th));`,
  },

  cosine: {
    code: (w) => `v += ${w} * vec2f(cos(PI*t.x) * cosh(t.y), -sin(PI*t.x) * sinh(t.y));`,
  },

  rings: {
    code: (w, _p, A) => `{ let rg_d = ${A(2)}*${A(2)} + 1e-6;
  let rg_r = mmod(r + rg_d, 2.0*rg_d) - rg_d + r*(1.0 - rg_d);
  v += ${w} * rg_r * vec2f(cos(ph), sin(ph)); }`,
  },

  fan: {
    code: (w, _p, A) => `{ let fn_t = PI * (${A(2)}*${A(2)} + 1e-6); let fn_h = 0.5*fn_t;
  var fn_a = ph + fn_h;
  if (mmod(ph + ${A(5)}, fn_t) > fn_h) { fn_a = ph - fn_h; }
  v += ${w} * r * vec2f(cos(fn_a), sin(fn_a)); }`,
  },

  blob: {
    params: [{ name: 'high', def: 1 }, { name: 'low', def: 0.3 }, { name: 'waves', def: 4 }],
    code: (w, p) => `{ let bl_r = r * (${p[1]} + 0.5*(${p[0]} - ${p[1]})*(1.0 + sin(${p[2]} * th)));
  v += ${w} * bl_r * vec2f(sin(th), cos(th)); }`,
  },

  pdj: {
    params: [{ name: 'a', def: 1 }, { name: 'b', def: 2 }, { name: 'c', def: 1 }, { name: 'd', def: 2 }],
    code: (w, p) => `v += ${w} * vec2f(sin(${p[0]}*t.y) - cos(${p[1]}*t.x), sin(${p[2]}*t.x) - cos(${p[3]}*t.y));`,
  },

  fan2: {
    params: [{ name: 'x', def: 0.5 }, { name: 'y', def: 1.2 }],
    code: (w, p) => `{ let f2_t = PI * (${p[0]}*${p[0]} + 1e-6); let f2_h = 0.5*f2_t;
  var f2_a = ph + f2_h;
  if (mmod(ph + ${p[1]}, f2_t) > f2_h) { f2_a = ph - f2_h; }
  v += ${w} * r * vec2f(sin(f2_a), cos(f2_a)); }`,
  },

  eyefish: { code: (w) => `v += (${w} * 2.0 / (r + 1.0)) * t;` },

  bubble: { code: (w) => `v += (${w} * 4.0 / (r2 + 4.0)) * t;` },

  cylinder: { code: (w) => `v += ${w} * vec2f(sin(t.x), t.y);` },

  perspective: {
    params: [{ name: 'angle', def: 0.62 }, { name: 'dist', def: 2.2 }],
    code: (w, p) => `{ let ps_t = ${w} * ${p[1]} / max(${p[1]} - t.y * sin(${p[0]}), 1e-6);
  v += ps_t * vec2f(t.x, t.y * cos(${p[0]})); }`,
  },

  noise: {
    code: (w) => `{ let nz_r = rnd(rs); let nz_a = rnd(rs) * 2.0 * PI;
  v += ${w} * nz_r * vec2f(t.x * cos(nz_a), t.y * sin(nz_a)); }`,
  },

  julian: {
    params: [{ name: 'power', def: 3 }, { name: 'dist', def: 1 }],
    code: (w, p) => `{ let jn_p = select(${p[0]}, 2.0, abs(${p[0]}) < 1e-6);
  let jn_k = floor(abs(jn_p) * rnd(rs));
  let jn_a = (ph + 2.0*PI*jn_k) / jn_p;
  let jn_r = pow(r2, 0.5 * ${p[1]} / jn_p);
  v += ${w} * jn_r * vec2f(cos(jn_a), sin(jn_a)); }`,
  },

  juliascope: {
    params: [{ name: 'power', def: 3 }, { name: 'dist', def: 1 }],
    code: (w, p) => `{ let js_p = select(${p[0]}, 2.0, abs(${p[0]}) < 1e-6);
  let js_k = floor(abs(js_p) * rnd(rs));
  var js_a = (2.0*PI*js_k + ph) / js_p;
  if (mmod(js_k, 2.0) > 0.5) { js_a = (2.0*PI*js_k - ph) / js_p; }
  let js_r = pow(r2, 0.5 * ${p[1]} / js_p);
  v += ${w} * js_r * vec2f(cos(js_a), sin(js_a)); }`,
  },

  blur: {
    code: (w) => `{ let bu_a = rnd(rs) * 2.0 * PI; let bu_r = rnd(rs);
  v += ${w} * bu_r * vec2f(cos(bu_a), sin(bu_a)); }`,
  },

  gaussian_blur: {
    code: (w) => `{ let gb_a = rnd(rs) * 2.0 * PI;
  let gb_r = rnd(rs) + rnd(rs) + rnd(rs) + rnd(rs) - 2.0;
  v += ${w} * gb_r * vec2f(cos(gb_a), sin(gb_a)); }`,
  },

  ngon: {
    params: [
      { name: 'power', def: 2 }, { name: 'sides', def: 5 },
      { name: 'corners', def: 1 }, { name: 'circle', def: 1 },
    ],
    code: (w, p) => `{ let ng_b = 2.0*PI / max(${p[1]}, 1.0);
  var ng_phi = ph - ng_b * floor(ph / ng_b);
  if (ng_phi > 0.5 * ng_b) { ng_phi -= ng_b; }
  let ng_amp = (${p[2]} * (1.0/max(cos(ng_phi), 1e-6) - 1.0) + ${p[3]}) / max(pow(r2, 0.5*${p[0]}), 1e-9);
  v += ${w} * ng_amp * t; }`,
  },

  curl: {
    params: [{ name: 'c1', def: 0.5 }, { name: 'c2', def: 0.25 }],
    code: (w, p) => `{ let cu_1 = 1.0 + ${p[0]}*t.x + ${p[1]}*(t.x*t.x - t.y*t.y);
  let cu_2 = ${p[0]}*t.y + 2.0*${p[1]}*t.x*t.y;
  let cu_r = ${w} / max(cu_1*cu_1 + cu_2*cu_2, 1e-9);
  v += cu_r * vec2f(t.x*cu_1 + t.y*cu_2, t.y*cu_1 - t.x*cu_2); }`,
  },

  rectangles: {
    params: [{ name: 'x', def: 1 }, { name: 'y', def: 1 }],
    code: (w, p) => `{ let rc_x = ${p[0]} + select(0.0, 1e-6, abs(${p[0]}) < 1e-6);
  let rc_y = ${p[1]} + select(0.0, 1e-6, abs(${p[1]}) < 1e-6);
  v += ${w} * vec2f((2.0*floor(t.x/rc_x) + 1.0)*rc_x - t.x, (2.0*floor(t.y/rc_y) + 1.0)*rc_y - t.y); }`,
  },

  tangent: {
    code: (w) => `v += ${w} * vec2f(sin(t.x) / (sign(cos(t.y)) * max(abs(cos(t.y)), 1e-6)), tan(t.y));`,
  },

  square: { code: (w) => `v += ${w} * vec2f(rnd(rs) - 0.5, rnd(rs) - 0.5);` },

  cross: {
    code: (w) => `{ let cr_s = t.x*t.x - t.y*t.y;
  v += ${w} * sqrt(1.0 / max(cr_s*cr_s, 1e-12)) * t; }`,
  },

  arch: {
    code: (w) => `{ let ar_a = rnd(rs) * PI * ${w}; let ar_s = sin(ar_a); let ar_c = cos(ar_a);
  v += ${w} * vec2f(ar_s, ar_s*ar_s / (sign(ar_c) * max(abs(ar_c), 1e-6))); }`,
  },
  rings2: {
    params: [{ name: 'val', def: 0.5 }],
    code: (w, p) => `{ let r2_d = ${p[0]}*${p[0]} + 1e-6;
  let r2_r = r - 2.0*r2_d*floor((r + r2_d)/(2.0*r2_d)) + r*(1.0 - r2_d);
  v += ${w} * r2_r * vec2f(sin(th), cos(th)); }`,
  },

  butterfly: {
    code: (w) => `{ let bf_y2 = 2.0*t.y;
  let bf_r = ${w} * 1.30294 * sqrt(abs(t.y * t.x) / max(t.x*t.x + bf_y2*bf_y2, 1e-9));
  v += bf_r * vec2f(t.x, bf_y2); }`,
  },

  cpow: {
    params: [{ name: 'r', def: 1 }, { name: 'i', def: 0.1 }, { name: 'power', def: 1.5 }],
    code: (w, p) => `{ let cp_p = select(${p[2]}, 1.0, abs(${p[2]}) < 1e-6);
  let cp_vc = ${p[0]} / cp_p; let cp_vd = ${p[1]} / cp_p;
  let cp_lnr = 0.5 * log(r2);
  let cp_a = cp_vc*ph + cp_vd*cp_lnr + (2.0*PI/cp_p) * floor(rnd(rs) * abs(cp_p));
  let cp_m = ${w} * exp(cp_vc*cp_lnr - cp_vd*ph);
  v += cp_m * vec2f(cos(cp_a), sin(cp_a)); }`,
  },

  elliptic: {
    code: (w) => `{ let el_t = r2 + 1.0; let el_x2 = 2.0*t.x;
  let el_xm = 0.5*(sqrt(max(el_t + el_x2, 0.0)) + sqrt(max(el_t - el_x2, 0.0)));
  let el_a = clamp(t.x / max(el_xm, 1e-9), -1.0, 1.0);
  let el_w = ${w} / (PI * 0.5);
  v += vec2f(el_w * asin(el_a), sign(t.y) * el_w * log(el_xm + sqrt(max(el_xm - 1.0, 0.0)))); }`,
  },

  escher: {
    params: [{ name: 'beta', def: 0.3 }],
    code: (w, p) => `{ let es_lnr = 0.5*log(r2);
  let es_vc = 0.5*(1.0 + cos(${p[0]}));
  let es_vd = 0.5*sin(${p[0]});
  let es_m = ${w} * exp(es_vc*es_lnr - es_vd*ph);
  let es_n = es_vc*ph + es_vd*es_lnr;
  v += es_m * vec2f(cos(es_n), sin(es_n)); }`,
  },

  exp: {
    code: (w) => `{ let xq_d = ${w} * exp(t.x); v += xq_d * vec2f(cos(t.y), sin(t.y)); }`,
  },

  log: {
    code: (w) => `v += ${w} * vec2f(0.5 * log(r2), ph);`,
  },

  foci: {
    code: (w) => `{ let fc_ex = exp(t.x) * 0.5; let fc_en = 0.25 / fc_ex;
  let fc_t = ${w} / max(fc_ex + fc_en - cos(t.y), 1e-6);
  v += fc_t * vec2f(fc_ex - fc_en, sin(t.y)); }`,
  },

  loonie: {
    code: (w) => `{ let lo_w2 = ${w}*${w};
  if (r2 < lo_w2) { v += ${w} * sqrt(max(lo_w2/r2 - 1.0, 0.0)) * t; }
  else { v += ${w} * t; } }`,
  },

  modulus: {
    params: [{ name: 'x', def: 0.5 }, { name: 'y', def: 0.5 }],
    code: (w, p) => `{ let mo_x = max(abs(${p[0]}), 1e-6); let mo_y = max(abs(${p[1]}), 1e-6);
  v += ${w} * vec2f(mmod(t.x + mo_x, 2.0*mo_x) - mo_x, mmod(t.y + mo_y, 2.0*mo_y) - mo_y); }`,
  },

  polar2: {
    code: (w) => `v += (${w} / PI) * vec2f(th, 0.5 * log(r2));`,
  },

  popcorn2: {
    params: [{ name: 'x', def: 0.5 }, { name: 'y', def: 0.5 }, { name: 'c', def: 3 }],
    code: (w, p) => `v += ${w} * vec2f(t.x + ${p[0]}*sin(tan(t.y*${p[2]})), t.y + ${p[1]}*sin(tan(t.x*${p[2]})));`,
  },

  scry: {
    code: (w) => `{ let sy_d = r * (r2 + 1.0/max(${w}, 1e-6));
  v += t / max(sy_d, 1e-9); }`,
  },

  separation: {
    params: [
      { name: 'x', def: 0.5 }, { name: 'y', def: 0.25 },
      { name: 'xinside', def: 0.05 }, { name: 'yinside', def: 0.05 },
    ],
    code: (w, p) => `{ let se_bx = sqrt(t.x*t.x + ${p[0]}*${p[0]});
  let se_by = sqrt(t.y*t.y + ${p[1]}*${p[1]});
  let se_x = select(-(se_bx + t.x*${p[2]}), se_bx - t.x*${p[2]}, t.x > 0.0);
  let se_y = select(-(se_by + t.y*${p[3]}), se_by - t.y*${p[3]}, t.y > 0.0);
  v += ${w} * vec2f(se_x, se_y); }`,
  },

  splits: {
    params: [{ name: 'x', def: 0.3 }, { name: 'y', def: 0.3 }],
    code: (w, p) => `v += ${w} * vec2f(t.x + sign(t.x)*${p[0]}, t.y + sign(t.y)*${p[1]});`,
  },

  stripes: {
    params: [{ name: 'space', def: 0.5 }, { name: 'warp', def: 0.5 }],
    code: (w, p) => `{ let st_rx = floor(t.x + 0.5);
  let st_ox = t.x - st_rx;
  v += ${w} * vec2f(st_ox*(1.0 - ${p[0]}) + st_rx, t.y + st_ox*st_ox*${p[1]}); }`,
  },

  whorl: {
    params: [{ name: 'inside', def: 0.5 }, { name: 'outside', def: 0.5 }],
    code: (w, p) => `{ let wh_d = ${w} - r;
  let wh_g = select(wh_d, 1e-6, abs(wh_d) < 1e-6);
  let wh_a = ph + select(${p[1]}, ${p[0]}, r < ${w}) / wh_g;
  v += ${w} * r * vec2f(cos(wh_a), sin(wh_a)); }`,
  },

  waves2: {
    params: [
      { name: 'scalex', def: 0.5 }, { name: 'scaley', def: 0.5 },
      { name: 'freqx', def: 2 }, { name: 'freqy', def: 2 },
    ],
    code: (w, p) => `v += ${w} * vec2f(t.x + ${p[0]}*sin(t.y*${p[2]}), t.y + ${p[1]}*sin(t.x*${p[3]}));`,
  },

  flower: {
    params: [{ name: 'petals', def: 5 }, { name: 'holes', def: 0.4 }],
    code: (w, p) => `{ let fl_r = (rnd(rs) - ${p[1]}) * cos(${p[0]} * ph);
  v += ${w} * fl_r * t / r; }`,
  },

  conic: {
    params: [{ name: 'eccentricity', def: 1 }, { name: 'holes', def: 0 }],
    code: (w, p) => `{ let co_ct = t.x / r;
  let co_r = ${w} * (rnd(rs) - ${p[1]}) * ${p[0]} / max(abs(1.0 + ${p[0]}*co_ct), 1e-6) * sign(1.0 + ${p[0]}*co_ct);
  v += co_r * t / r; }`,
  },

  parabola: {
    params: [{ name: 'height', def: 0.5 }, { name: 'width', def: 1 }],
    code: (w, p) => `{ let pa_sr = sin(r); let pa_cr = cos(r);
  v += ${w} * vec2f(${p[0]}*pa_sr*pa_sr*rnd(rs), ${p[1]}*pa_cr*rnd(rs)); }`,
  },

  bent2: {
    params: [{ name: 'x', def: 1.5 }, { name: 'y', def: 1 }],
    code: (w, p) => `v += ${w} * vec2f(select(t.x, t.x*${p[0]}, t.x < 0.0), select(t.y, t.y*${p[1]}, t.y < 0.0));`,
  },

  pie: {
    params: [
      { name: 'slices', def: 6 }, { name: 'rotation', def: 0 }, { name: 'thickness', def: 0.5 },
    ],
    code: (w, p) => `{ let pi_n = max(${p[0]}, 1.0);
  let pi_s = floor(rnd(rs) * pi_n + 0.5);
  let pi_a = ${p[1]} + (2.0*PI / pi_n) * (pi_s + rnd(rs)*${p[2]});
  v += ${w} * rnd(rs) * vec2f(cos(pi_a), sin(pi_a)); }`,
  },

  hemisphere: {
    code: (w) => `v += (${w} / sqrt(r2 + 1.0)) * t;`,
  },

  // ---- Direct-color variations: paint the palette coordinate from geometry ----
  dc_linear: {
    params: [{ name: 'offset', def: 0 }, { name: 'angle', def: 0 }, { name: 'scale', def: 0.5 }],
    code: (w, p) => `{ v += ${w} * t;
  *cp = fract((cos(${p[1]})*t.x + sin(${p[1]})*t.y) * ${p[2]} + ${p[0]}); }`,
  },

  dc_radial: {
    params: [{ name: 'scale', def: 0.7 }, { name: 'offset', def: 0 }],
    code: (w, p) => `{ v += ${w} * t;
  *cp = fract(r * ${p[0]} + ${p[1]}); }`,
  },

  dc_angle: {
    params: [{ name: 'count', def: 2 }, { name: 'offset', def: 0 }],
    code: (w, p) => `{ v += ${w} * t;
  *cp = fract((ph / (2.0 * PI) + 0.5) * ${p[0]} + ${p[1]}); }`,
  },

  dc_bubble: {
    params: [{ name: 'scale', def: 1 }, { name: 'offset', def: 0 }],
    code: (w, p) => `{ let dcb = 4.0 / (r2 + 4.0);
  v += ${w} * dcb * t;
  *cp = fract(dcb * ${p[0]} + ${p[1]}); }`,
  },

  // ---- JWildfire mobius3D_with_inverse (Mobius3DWithInverseFunc): quaternion Möbius transform, or its inverse
  // (50/50 per point); the matrix is normalised by det² unless normalize = 0 ----
  mobius3D_with_inverse: {
    params: [
      { name: 'a_re', def: 2 }, { name: 'a_im', def: 0 }, { name: 'aj', def: 0 }, { name: 'ak', def: 0 },
      { name: 'b_re', def: 0 }, { name: 'b_im', def: -1 }, { name: 'bj', def: 0 }, { name: 'bk', def: 0 },
      { name: 'c_re', def: 0 }, { name: 'c_im', def: -1 }, { name: 'cj', def: 0 }, { name: 'ck', def: 0 },
      { name: 'd_re', def: 0 }, { name: 'd_im', def: 0 }, { name: 'dj', def: 0 }, { name: 'dk', def: 0 },
      { name: 'normalize', def: 1, int: true },
    ],
    flags: ['3d', 'z'],
    types: ['3D'],
    funcNames: ['qmul', 'qrecip'],
    funcs: `fn qmul(a: vec4f, b: vec4f) -> vec4f {
  return vec4f(a.x * b.x - a.y * b.y - a.z * b.z - a.w * b.w, a.x * b.y + a.y * b.x + a.z * b.w - a.w * b.z, a.x * b.z - a.y * b.w + a.z * b.x + a.w * b.y, a.x * b.w + a.y * b.z - a.z * b.y + a.w * b.x);
}

fn qrecip(q: vec4f) -> vec4f {
  let n2 = dot(q, q);
  return vec4f(q.x, -q.y, -q.z, -q.w) / n2;
}`,
    code: (w, p) => `{
  var qa = vec4f(${p[0]}, ${p[1]}, ${p[2]}, ${p[3]}); var qb = vec4f(${p[4]}, ${p[5]}, ${p[6]}, ${p[7]});
  var qc = vec4f(${p[8]}, ${p[9]}, ${p[10]}, ${p[11]}); var qd = vec4f(${p[12]}, ${p[13]}, ${p[14]}, ${p[15]});
  if (${p[16]} != 0.0) {
    let det = qmul(qa, qd) - qmul(qb, qc);
    let rden = qrecip(qmul(det, det)); // div1(x, denom) = recip(denom)·x
    qa = qmul(rden, qa); qb = qmul(rden, qb); qc = qmul(rden, qc); qd = qmul(rden, qd);
  }
  if (rnd(rs) >= 0.5) { let ta = qa; qa = qd; qd = ta; qb = -qb; qc = -qc; } // the inverse matrix [d, −b, −c, a]
  let zin = vec4f(t.x, t.y, z_, 0.0);
  let zout = qmul(qrecip(qmul(zin, qc) + qd), qmul(zin, qa) + qb);
  v += ${w} * zout.xy;
  pz_ += ${w} * zout.z;
}`,
  },

  // ---- JWildfire pre_stabilize (Rick Sidwell): with probability p/1000 the input point jumps to one of n
  // seeded random points (java.util.Random(seed) stream: x, y pairs; colours 0.5, 0.25, 0.75, 0.125, …) ----
  pre_stabilize: {
    params: [{ name: 'n', def: 4, int: true }, { name: 'seed', def: 12345, int: true }, { name: 'p', def: 0.1 }, { name: 'dc', def: 0, int: true }],
    priority: -1,
    flags: ['dc'],
    types: ['ZTRANSFORM', 'DC', 'PRE'],
    funcNames: ['jrand_', 'jrand_make', 'jrand_next', 'jrand_nextDouble'],
    funcs: `struct jrand_ {
  s0: i32,
  s1: i32,
  s2: i32,
}

fn jrand_make(seed: i32) -> jrand_ {
  var r_: jrand_;
  r_.s0 = ((seed & 65535) ^ 58989);
  r_.s1 = (((seed >> 16) & 65535) ^ 57068);
  r_.s2 = (select(0, 65535, (seed < 0)) ^ 5);
  return r_;
}

fn jrand_next(r_: ptr<function, jrand_>, bits: i32) -> i32 {
  var a0: u32 = u32((*r_).s0);
  var a1: u32 = u32((*r_).s1);
  var a2: u32 = u32((*r_).s2);
  var t0: u32 = ((a0 * 58989) + 11);
  var r0: u32 = (t0 & 65535);
  var c0: u32 = (t0 >> 16);
  var t1a: u32 = ((a0 * 57068) + c0);
  var c1a: u32 = (t1a >> 16);
  var t1b: u32 = ((a1 * 58989) + (t1a & 65535));
  var r1: u32 = (t1b & 65535);
  var c1: u32 = (c1a + (t1b >> 16));
  var r2_: u32 = (((((a0 * 5) + (a1 * 57068)) + (a2 * 58989)) + c1) & 65535);
  (*r_).s0 = i32(r0);
  (*r_).s1 = i32(r1);
  (*r_).s2 = i32(r2_);
  var hi: u32 = ((r2_ << 16) | r1);
  return i32((hi >> u32((32 - bits))));
}

fn jrand_nextDouble(r_: ptr<function, jrand_>) -> f32 {
  return ((f32(jrand_next(r_, 26)) * (1.0 / 67108864.0)) + (f32(jrand_next(r_, 27)) * (1.0 / 9007199254740992.0)));
}`,
    code: (_w, p) => `{
  let ps_n = max(i32(${p[0]}), 1);
  if (wstart_ || rnd(rs) < ${p[2]} / 1000.0) { // JWildfire: on the instance's first call, then with probability p/1000
    let ps_i = min(i32(rnd(rs) * f32(ps_n)), ps_n - 1);
    var ps_r = jrand_make(i32(${p[1]}));
    var ps_x = 0.0; var ps_y = 0.0; var ps_c = 0.5; var ps_next = 0.5; var ps_delta = 1.0;
    for (var k = 0; k <= ps_i; k = k + 1) {
      ps_x = jrand_nextDouble(&ps_r) * 2.0 - 1.0;
      ps_y = jrand_nextDouble(&ps_r) * 2.0 - 1.0;
      ps_c = ps_next;
      ps_next += ps_delta;
      if (ps_next >= 1.0) { ps_delta /= 2.0; ps_next = ps_delta / 2.0; }
    }
    t = vec2f(ps_x, ps_y); z_ = 0.0;
    if (${p[3]} != 0.0) { *cp = ps_c; }
    r2 = max(dot(t, t), 1e-12); r = sqrt(r2); th = atan2(t.x, t.y); ph = atan2(t.y, t.x);
  }
}`,
  },

  // ---- JWildfire inversion (InversionFunc): generalised circle inversion in a parametric shape (circle, ellipse,
  // hyperbola, regular polygon, rhodonea, superellipse, supershape) with p-norms, ring constraints, pass-through,
  // shape drawing and direct-colour measures; guides are an editor-only feature ----
  inversion: {
    params: [
      { name: 'scale', def: 1 }, { name: 'rotation', def: 0 }, { name: 'shape', def: 0, int: true },
      { name: 'imode', def: 0, int: true }, { name: 'hide_uninverted', def: 0, int: true },
      { name: 'a', def: 1 }, { name: 'b', def: 1 }, { name: 'c', def: 0 }, { name: 'd', def: 0 }, { name: 'e', def: 0 }, { name: 'f', def: 0 },
      { name: 'ring_mode', def: 0, int: true }, { name: 'ring_scale', def: 1 },
      { name: 'pnorm_point', def: 2 }, { name: 'pnorm_shape', def: 2 }, { name: 'pnorm_pmod', def: 1 }, { name: 'pnorm_smod', def: 1 },
      { name: 'draw_shape', def: 0 }, { name: 'shape_thickness', def: 0 }, { name: 'passthrough', def: 0 }, { name: 'guides_enabled', def: 1, int: true },
      { name: 'color_measure', def: 0, int: true }, { name: 'color_gradient', def: 1, int: true }, { name: 'color_low_threshold', def: 0 }, { name: 'color_high_threshold', def: 1 },
    ],
    flags: ['dc', 'hide', 'z'],
    types: ['2D', 'DC'],
    funcNames: ['invCurve', 'invPeriod', 'invMaxCurve'],
    funcs: `fn invCurve(shape: i32, tin: f32, rot: f32, sc: f32, a: f32, b: f32, c: f32, d: f32, e: f32, f: f32) -> vec3f {
  // InversionFunc.ParametricShape.getCurvePoint: (x, y, r) of the shape at polar angle tin (params a..f, scale, rotation)
  let t = tin - rot;
  var r = sc;
  switch shape {
    case 1: { r = (a * b) / sqrt((b * cos(t)) * (b * cos(t)) + (a * sin(t)) * (a * sin(t))) * sc; }
    case 2: { r = sqrt((a * a * b * b) / ((b * b * cos(t) * cos(t)) - (a * a * sin(t) * sin(t)))) * sc; }
    case 3: { let th_ = abs(t % (2.0 * PI)); let n = floor(a); r = cos(PI / n) / cos(th_ % (2.0 * PI / n) - PI / n) * sc; }
    case 4: { r = (cos((a / b) * t) + c) * sc; }
    case 5: { r = (a * b) / pow(pow(abs(a * sin(t)), c) + pow(abs(b * cos(t)), c), 1.0 / c) * sc; }
    case 6: { r = pow(pow(abs(cos(c * t / 4.0) / a), e) + pow(abs(sin(c * t / 4.0) / b), f), -1.0 / d) * sc; }
    default: { r = sc; }
  }
  return vec3f(r * cos(tin), r * sin(tin), r);
}

fn invPeriod(shape: i32, a: f32, b: f32, c: f32) -> f32 {
  // Rhodonea.calcPeriod (the other shapes have period 2π)
  if (shape != 4) { return 2.0 * PI; }
  let k = a / b;
  if (k % 1.0 == 0.0) {
    if (k % 2.0 == 0.0) { return 2.0 * PI; }
    return select(PI, 2.0 * PI, c != 0.0);
  }
  if (a % 1.0 == 0.0 && b % 1.0 == 0.0) {
    var kn = i32(abs(a)); var kd = i32(abs(b));
    var x = kn; var y = kd;
    while (y != 0) { let tmp = x % y; x = y; y = tmp; }
    let g = max(x, 1);
    if (g != 1) { kn = kn / g; kd = kd / g; }
    return select(f32(kd) * PI, f32(kd) * 2.0 * PI, kn % 2 == 0 || kd % 2 == 0);
  }
  return 2.0 * PI;
}

fn invMaxCurve(shape: i32, tin: f32, rot: f32, sc: f32, a: f32, b: f32, c: f32, d: f32, e: f32, f: f32) -> vec3f {
  // ParametricShape.getMaxCurvePoint: rhodonea can cross a ray several times — take the farthest of period/2π samples spaced π apart
  if (shape != 4) { return invCurve(shape, tin, rot, sc, a, b, c, d, e, f); }
  var out = vec3f(0.0, 0.0, -0.0001);
  let cnt = i32(invPeriod(shape, a, b, c) / (2.0 * PI));
  for (var i = 0; i < cnt; i = i + 1) {
    let q = invCurve(shape, tin + f32(i) * PI, rot, sc, a, b, c, d, e, f);
    if (abs(q.z) > out.z) { out = vec3f(q.xy, abs(q.z)); }
  }
  return out;
}`,
    code: (w, p) => `{
  let iv_shape = i32(${p[2]}); let iv_rot = PI * ${p[1]}; let iv_sc = ${p[0]};
  let iv_a = ${p[5]}; let iv_b = ${p[6]}; let iv_c = ${p[7]}; let iv_d = ${p[8]}; let iv_e = ${p[9]}; let iv_f = ${p[10]};
  var iv_done = false;
  if (${p[17]} > 0.0 && rnd(rs) < ${p[17]}) {
    let cpnt = invCurve(iv_shape, rnd(rs) * invPeriod(iv_shape, iv_a, iv_b, iv_c), iv_rot, iv_sc, iv_a, iv_b, iv_c, iv_d, iv_e, iv_f);
    v += cpnt.xy;
    if (${p[18]} != 0.0) { v += 0.01 * (vec2f(rnd(rs), rnd(rs)) - 0.5) * ${p[18]}; }
    iv_done = true;
  }
  if (!iv_done && ${p[19]} > 0.0 && rnd(rs) < ${p[19]}) { v += t; iv_done = true; }
  if (!iv_done) {
    let tin = atan2(t.y, t.x);
    let rin = length(t);
    let cur = invMaxCurve(iv_shape, tin, iv_rot, iv_sc, iv_a, iv_b, iv_c, iv_d, iv_e, iv_f);
    let rcurve = cur.z;
    var doInv = true;
    let imode = i32(${p[3]});
    if (imode == 1) { doInv = rin > rcurve; } else if (imode == 2) { doInv = rin < rcurve; }
    let ring_mode = i32(${p[11]}); let ring_scale = ${p[12]};
    if (doInv && ring_mode != 0 && ring_scale != 1.0) {
      var rmin = ring_scale * iv_sc; var rmax = (iv_sc * iv_sc) / rmin;
      if (ring_scale > iv_sc) { rmax = ring_scale * iv_sc; rmin = (iv_sc * iv_sc) / rmax; }
      if (ring_mode == 1) { doInv = rin >= rmin && rin <= rmax; } else if (ring_mode == 2) { doInv = rin <= rmin || rin >= rmax; }
    }
    if (doInv) {
      var num_scale = rcurve * rcurve;
      if (!(${p[14]} == 2.0 && ${p[16]} == 1.0)) { num_scale = pow(pow(abs(cur.x), ${p[14]}) + pow(abs(cur.y), ${p[14]}), 2.0 / (${p[14]} * ${p[16]})); }
      var denom_scale = dot(t, t);
      if (!(${p[13]} == 2.0 && ${p[15]} == 1.0)) { denom_scale = pow(pow(abs(t.x), ${p[13]}) + pow(abs(t.y), ${p[13]}), 2.0 / (${p[13]} * ${p[15]})); }
      let iscale = num_scale / denom_scale;
      v += ${w} * iscale * t;
      if ((P.flags & 1u) != 0u) { pz_ += ${w} * z_; }
      *hd = false;
      let cm = i32(${p[21]});
      if (cm != 0) {
        var val = 0.0;
        if (cm == 1) { val = length(v - cur.xy); }
        else if (cm == 2) { val = length(t - cur.xy); }
        else if (cm == 3) { val = length(v - t); }
        else if (cm == 4) { let ci = (iv_sc * iv_sc) / dot(t, t) * ${w}; val = length(v) / length(ci * t); }
        if (cm >= 1 && cm <= 4) {
          var lo = ${p[23]}; var hi = ${p[24]};
          if (lo > hi) { let tmp = lo; lo = hi; hi = tmp; }
          var col: f32;
          if (i32(${p[22]}) == 2) {
            if (val < lo) { val = hi - ((lo - val) % (hi - lo)); } else if (val > hi) { val = lo + ((val - lo) % (hi - lo)); }
            col = (val - lo) / (hi - lo);
          } else {
            col = select(select((val - lo) / (hi - lo), 1.0, val >= hi), 0.0, val < lo);
          }
          *cp = clamp(col, 0.0, 1.0);
        }
      }
    } else {
      v += t;
      if ((P.flags & 1u) != 0u) { pz_ += z_; }
      *hd = ${p[4]} != 0.0;
    }
  }
}`,
  },

  // ---- JWildfire obj_mesh_primitive_wf / obj_mesh_wf: a random point on a mesh (src/core/meshes.ts) ----
  // Params in JWildfire's order; the colour/displacement maps need images (never active here, their file names
  // round-trip as resources); receive_only_shadows is accepted but not modelled. Hidden slots: cdf base, face
  // count, triangle base into the shared mesh buffer (codegen data hook, mesh binding 12).
  // obj_mesh_wf samples the user's OBJ file named by its `obj_filename` resource (loaded through the transform
  // editor into the browser's mesh store) and, exactly like JWildfire when the name is empty or the file is
  // missing, the default ±1 cube otherwise.
  obj_mesh_primitive_wf: {
    params: [{ name: 'primitive', def: 0, int: true }, ...MESH_PARAMS],
    extra: 3,
    res: ['colormap_filename', 'displ_map_filename'],
    flags: ['3d', 'z', 'mesh'],
    types: ['3D', 'BASE_SHAPE'],
    funcNames: ['meshPick'],
    funcs: MESH_FUNCS,
    code: (w, p) => meshCode(w, p, 1),
  },
  obj_mesh_wf: {
    params: [...MESH_PARAMS],
    extra: 3,
    res: ['obj_filename', 'colormap_filename', 'displ_map_filename'],
    flags: ['3d', 'z', 'mesh'],
    types: ['3D', 'BASE_SHAPE'],
    funcNames: ['meshPick'],
    funcs: MESH_FUNCS,
    code: (w, p) => meshCode(w, p, 0),
  },

  // ---- JWildfire subflame_wf: a nested flame's chaos game (its first layer) run one step per call, the point returned
  // scaled/rotated/offset. The sub-flame is the instance's `flame` resource (XML; JWildfire's default flame until set);
  // codegen compiles it into the kernel (sub-xform functions + weight tables + palette, src/gpu/codegen.ts) and the
  // hidden slot is the compiled instance index. The amount is ignored like JWildfire's (pVarTP += q, no pAmount);
  // color_mode −1 leaves the colour, 0 takes the sub-flame's colour index, 1..4 a channel of its palette colour, −2 the
  // palette colour itself as a direct RGB colour. Only sequences (flame_is_sequence) are not modelled (accepted, ignored).
  subflame_wf: {
    params: [
      { name: 'scale', def: 1 }, { name: 'angle', def: 0 }, { name: 'offset_x', def: 0 }, { name: 'offset_y', def: 0 }, { name: 'offset_z', def: 0 },
      { name: 'colorscale_z', def: 0 }, { name: 'color_mode', def: -1, int: true },
      { name: 'flame_is_sequence', def: 0, int: true }, { name: 'flame_sequence_start', def: 1, int: true }, { name: 'flame_sequence_end', def: 0, int: true },
      { name: 'flame_sequence_repeat', def: 1, int: true }, { name: 'flame_sequence_digits', def: 4, int: true },
    ],
    extra: 1,
    res: ['flame', 'flame_filename'],
    resDef: { flame: DFLT_SUBFLAME_XML },
    flags: ['3d', 'z', 'dc', 'hide', 'subflame'],
    types: ['3D', 'BASE_SHAPE'],
    code: (_w, p) => `{ let sq_ = subflameAny(u32(${p[12]}), rs, cp, hd, rgb, ${p[0]}, ${p[1]}, ${p[2]}, ${p[3]}, ${p[4]}, ${p[5]}, i32(${p[6]}));
    v += sq_.xy;
    pz_ += sq_.z; }`,
  },
};

/** Verified JWildfire ports that we deliberately do NOT let override the
 *  hand-written entry, with the reason. Keep this list short and justified. */
export const PREFER_HAND: Record<string, string> = {
  // JWildfire's rings ignores the variation weight (Java: no pAmount; its GPU
  // code likewise). flam3/Apophysis multiply by weight and so do our presets
  // (Clockwork mixes linear .6 + rings .35) — keep flam3 semantics.
  rings: 'JWildfire ignores the weight; flam3/Apophysis apply it',
};

/** The registry. Hand-written entries are present from the start (fallbacks); the
 *  verified JWildfire ports (variations.jwf.ts, ~2 MB, its own cached chunk) are merged
 *  in by `loadJwfVariations()` — main.ts awaits it alongside WebGPU init before the
 *  first render, so by the time anything compiles a flame the registry is complete
 *  (except PREFER_HAND). The object and the name arrays below are mutated in place so
 *  every importer keeps working with the same references. */
export const VARIATIONS: Record<string, VariationDef> = { ...HAND_VARIATIONS };

/** Sorted names of everything in VARIATIONS (kept in place, refreshed after the ports load). */
export const VARIATION_NAMES: string[] = Object.keys(VARIATIONS).sort((a, b) => a.localeCompare(b));

let jwfLoad: Promise<void> | null = null;
/** Load and merge the JWildfire ports (idempotent; resolves immediately once done). */
export function loadJwfVariations(): Promise<void> {
  if (!jwfLoad) {
    jwfLoad = import('./variations.jwf.ts').then(({ JWF_VARIATIONS }) => {
      for (const [name, def] of Object.entries(JWF_VARIATIONS) as [string, JwfVariationDef][]) {
        if (def.verified && !(name in PREFER_HAND && name in HAND_VARIATIONS)) VARIATIONS[name] = def;
      }
      VARIATION_NAMES.splice(0, VARIATION_NAMES.length, ...Object.keys(VARIATIONS).sort((a, b) => a.localeCompare(b)));
    });
  }
  return jwfLoad;
}
/** True once loadJwfVariations() has merged the ports. */
export function jwfVariationsLoaded(): boolean { return VARIATION_NAMES.length > Object.keys(HAND_VARIATIONS).length; }

/** The hand-written subset (exposed for the oracle harness). */
export { HAND_VARIATIONS };

/** The flam3 core set — what most flames are built from; pinned first in the picker. */
export const CLASSIC_VARIATIONS = [
  'linear', 'sinusoidal', 'spherical', 'swirl', 'horseshoe', 'polar', 'handkerchief', 'heart', 'disc',
  'spiral', 'hyperbolic', 'diamond', 'ex', 'julia', 'bent', 'waves', 'fisheye', 'popcorn', 'exponential',
  'power', 'cosine', 'rings', 'fan', 'blob', 'pdj', 'fan2', 'rings2', 'eyefish', 'bubble', 'cylinder',
  'perspective', 'noise', 'julian', 'juliascope', 'blur', 'gaussian_blur', 'radial_blur', 'pie', 'ngon',
  'curl', 'rectangles', 'arch', 'tangent', 'square', 'rays', 'blade', 'secant', 'twintrian', 'cross',
  'polar2', 'elliptic', 'escher', 'foci', 'lazysusan', 'loonie', 'pre_blur', 'modulus', 'oscilloscope',
  'popcorn2', 'scry', 'separation', 'split', 'splits', 'stripes', 'wedge', 'whorl', 'waves2', 'exp', 'log',
  'sin', 'cos', 'tan', 'sec', 'csc', 'cot', 'sinh', 'cosh', 'tanh', 'auger', 'flux', 'mobius', 'bwraps',
  'hemisphere', 'dc_linear', 'crop', 'post_curl',
]; // all present once the ports are loaded (the picker filters by VARIATION_NAMES)

/** Type tags for a variation (JWildfire's where known, inferred for hand-written entries). */
export function variationTypes(name: string): string[] {
  const def = VARIATIONS[name];
  if (!def) return [];
  if (def.types?.length) return def.types;
  const t = ['2D'];
  if (name.startsWith('dc_')) t.push('DC');
  if (/blur/.test(name)) t.push('BLUR');
  if (name.startsWith('pre_')) t.push('PRE');
  if (name.startsWith('post_')) t.push('POST');
  return t;
}

export function variationParamCount(name: string): number {
  return VARIATIONS[name]?.params?.length ?? 0;
}

export function defaultParams(name: string): Record<string, number> {
  const out: Record<string, number> = {};
  for (const p of VARIATIONS[name]?.params ?? []) out[p.name] = p.def;
  return out;
}
