#!/usr/bin/env node
// Generates src/core/plotPresets.ts from JWildfire's formula preset files
// (src/org/jwildfire/create/tina/variation/plot/*_presets.txt) the way WFFuncPresets.parsePresets reads them:
// blocks start at "##<id>", a token is the first line starting with it (prefix match, like Java's indexOf("\n" + token)),
// the value is what follows "=" up to an optional "---" comment; numeric values are JEP expressions (`2.0 * pi`);
// a token a family does not declare is ignored, a missing one is 0.0 (parseParam's null → 0.0).
//   node scripts/jwf-port/plot-presets.mjs <path-to-jwf-tree>
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const jwf = process.argv[2];
if (!jwf) { console.error('usage: plot-presets.mjs <jwf tree>'); process.exit(1); }
const dir = join(jwf, 'src/org/jwildfire/create/tina/variation/plot');

// [file, export name, formula tokens, numeric tokens] — the tokens each *WFFuncPresets.parsePreset reads
const FAMILIES = [
  ['yplot2d_wf_presets.txt', 'YPLOT2D_PRESETS', ['formula'], ['xmin', 'xmax', 'param_a', 'param_b', 'param_c', 'param_d', 'param_e', 'param_f']],
  ['yplot3d_wf_presets.txt', 'YPLOT3D_PRESETS', ['formula'], ['xmin', 'xmax', 'zmin', 'zmax', 'param_a', 'param_b', 'param_c', 'param_d', 'param_e', 'param_f']],
  ['parplot2d_wf_presets.txt', 'PARPLOT2D_PRESETS', ['xformula', 'yformula', 'zformula'], ['umin', 'umax', 'vmin', 'vmax', 'param_a', 'param_b', 'param_c', 'param_d', 'param_e', 'param_f']],
  ['polarplot2d_wf_presets.txt', 'POLARPLOT2D_PRESETS', ['formula'], ['tmin', 'tmax', 'param_a', 'param_b', 'param_c', 'param_d', 'param_e', 'param_f']],
  ['polarplot3d_wf_presets.txt', 'POLARPLOT3D_PRESETS', ['formula'], ['tmin', 'tmax', 'umin', 'umax', 'cylindrical', 'param_a', 'param_b', 'param_c', 'param_d', 'param_e', 'param_f']],
  ['isosfplot3d_wf_presets.txt', 'ISOSFPLOT3D_PRESETS', ['formula'], ['xmin', 'xmax', 'ymin', 'ymax', 'zmin', 'zmax', 'param_a', 'param_b', 'param_c', 'param_d', 'param_e', 'param_f']],
  ['knots3d_wf_presets.txt', 'KNOTS3D_PRESETS', ['xformula', 'yformula', 'zformula'], ['steps', 'radius', 'facets', 'param_a', 'param_b', 'param_c', 'param_d', 'param_e', 'param_f', 'param_g', 'param_h']],
];

/** JEP expression → number (the preset files only use numbers, pi and + - * / parentheses) */
function jep(s) {
  s = s.replace(/;\s*$/, ''); // JEP tolerates a trailing ';' (parplot2d #4)
  if (!/^[\d.\s+\-*/()eEpiM_PI]+$/.test(s)) throw new Error(`unexpected preset value "${s}"`);
  const js = s.replace(/\bM_PI\b/g, 'Math.PI').replace(/\bpi\b/g, 'Math.PI');
  return Function(`"use strict"; return (${js});`)();
}
function parseToken(block, token) {
  const p1 = block.indexOf('\n' + token);
  if (p1 < 0) return null;
  let p2 = block.indexOf('\n', p1 + 1); if (p2 < 0) p2 = block.length;
  let line = block.substring(p1 + token.length, p2).trim();
  const p3 = line.indexOf('='); if (p3 < 0) return null;
  line = line.substring(p3 + 1);
  const p4 = line.indexOf('---'); if (p4 > 0) line = line.substring(0, p4);
  return line.trim();
}
const out = [`// JWildfire formula presets of the plot family and knots3D (JWildfire's plot/*_presets.txt — formulas by Andreas
// Maschke, Rick Sidwell, Frank Baumann, Jesus Sosa and other contributors; LGPL 2.1+, see NOTICE.md). Generated by
// scripts/jwf-port/plot-presets.mjs — do not edit by hand. Each entry holds exactly what JWildfire's preset parser
// reads: a missing numeric token is 0.
export interface PlotPreset { id: number; f: Record<string, string>; p: Record<string, number> }
`];
for (const [file, name, ftoks, ntoks] of FAMILIES) {
  const txt = readFileSync(join(dir, file), 'utf8').replace(/\r\n/g, '\n');
  const entries = [];
  let blockStart = -1;
  while (blockStart < txt.length) {
    blockStart = txt.indexOf('##', blockStart + 1);
    if (blockStart < 0) break;
    let blockEnd = txt.indexOf('##', blockStart + 2);
    if (blockEnd < 0) blockEnd = txt.length;
    const block = txt.substring(blockStart - 1, blockEnd);
    const idLine = block.substring(block.indexOf('##') + 2).split('\n')[0].trim();
    const id = parseInt(idLine, 10);
    if (!Number.isInteger(id)) { console.warn(`${file}: bad id "${idLine}"`); continue; }
    const f = {}; const p = {};
    for (const t of ftoks) { const v = parseToken(block, t); if (v === null) console.warn(`${file} #${id}: no ${t}`); f[t] = v ?? ''; }
    for (const t of ntoks) { const v = parseToken(block, t); p[t] = v === null ? 0 : jep(v); }
    if (entries.some((e) => e.id === id)) { console.warn(`${file}: duplicate id ${id}`); continue; }
    entries.push({ id, f, p });
  }
  entries.sort((a, b) => a.id - b.id);
  out.push(`export const ${name}: PlotPreset[] = [\n${entries.map((e) => '  ' + JSON.stringify(e)).join(',\n')},\n];\n`);
  console.log(`${name}: ${entries.length} presets (ids ${entries[0].id}..${entries[entries.length - 1].id})`);
}
writeFileSync(new URL('../../src/core/plotPresets.ts', import.meta.url), out.join('\n'));
